using System;
using System.Collections.Generic;

namespace EnterpriseOps.Services
{
    /// <summary>
    /// The documented Wisej.NET API surface — the boundary rule of the prompt header: <b>do not use an API
    /// unless it exists in the official Wisej.NET documentation</b> (docs/PromptLibrary.md, rule 5).
    ///
    /// The two lists below are not hand-written. They were extracted from <c>Wisej.Framework.xml</c>, the XML
    /// documentation file shipped inside the <c>Wisej-4</c> 4.1.0 NuGet package and the same source the
    /// documentation site is generated from: every documented property, method and field of a
    /// <c>Wisej.Web</c> / <c>Wisej.Core</c> / <c>Wisej.Base</c> type, plus every documented type name.
    /// Regenerating them for a new release is a one-line script — see README.md, "Regenerating the catalog".
    ///
    /// Checklist rule Q1 uses it: when generated code calls a member on something that is clearly a Wisej.NET
    /// control (a control-named field, or one of the platform's static entry points) and that member is not
    /// in this catalog, the change stops at review. That is how <c>grid.EnableSmartVirtualScroll()</c> — a
    /// plausible, invented API — never reaches main.
    ///
    /// Static, but not static <em>state</em>: the catalog is immutable reference data built once per process
    /// and shared by every session. Checklist Q2 objects to statics that remember a user, a tenant or a
    /// selection — see Security/Permissions.cs for the same distinction.
    /// </summary>
    public static class DocumentedApiCatalog
    {
        /// <summary>Where the catalog came from — quoted in every Q1 finding so the reviewer can check it.</summary>
        public const string Source = "Wisej.Framework.xml (Wisej-4 4.1.0)";

        /// <summary>Number of documented members the catalog knows.</summary>
        public static int MemberCount => Members.Count;

        /// <summary>Number of documented type names the catalog knows.</summary>
        public static int TypeCount => Types.Count;

        /// <summary>True when <paramref name="member"/> is a documented Wisej.NET property, method or field.</summary>
        public static bool IsDocumented(string member)
            => !string.IsNullOrEmpty(member) && Members.Contains(member);

        /// <summary>True when <paramref name="name"/> is a documented Wisej.NET type (Button, DataGridView, Page…).</summary>
        public static bool IsDocumentedType(string name)
            => !string.IsNullOrEmpty(name) && Types.Contains(name);

        private static readonly HashSet<string> Members;
        private static readonly HashSet<string> Types;

        /// <summary>
        /// Built in a static constructor, not in a field initializer: static field initializers run in
        /// textual order, and the name tables live at the bottom of this file for readability. A field
        /// initializer here would read them before they exist — and compile happily.
        /// </summary>
        static DocumentedApiCatalog()
        {
            Members = Build(MemberNames);
            Types = Build(TypeNames);
        }

        private static HashSet<string> Build(string[] lines)
        {
            var set = new HashSet<string>(StringComparer.Ordinal);
            foreach (string line in lines)
            {
                foreach (string name in line.Split(' '))
                {
                    if (name.Length > 0)
                        set.Add(name);
                }
            }
            return set;
        }

        // ── documented members (properties, methods, fields) ─────────────────────────────────────────────
        private static readonly string[] MemberNames =
        {
            "_commandSources A Abort AbortRetryIgnore Above Absolute Accelerators AcceptButton AcceptsReturn AcceptsTab",
            "AccessibleDescription AccessibleName Accordion AcrossFirst Action Actions Activate ActivateControl Active",
            "ActiveControl ActiveCount ActiveForm ActiveLinkColor ActiveMdiChild ActivePage ActiveProfile",
            "ActiveSessionCount ActiveWindow ActualIndex Add AddAfter AddAnnuallyBoldedDate AddBefore AddBoldedDate",
            "AddClientEventListener AddColumns AddCopies AddCopy AddCore AddCssClass AddEventFilter AddExtension AddFirst",
            "AddHandler AddInternal AdditionalName AddListener AddMonthlyBoldedDate AddNew AddNewItem AddNewRow",
            "AddOwnedForm AddRange AddRangeInternal AddressLevel1 AddressLevel2 AddressLevel3 AddressLevel4 AddressLine1",
            "AddressLine2 AddressLine3 AddRows AddStandardItems AddState AddSummaryRows AddToControls AddTranslation",
            "AddTranslationInternal AddWeakHandler AdjustFormScrollbars AdjustItemHeights AdjustRect AdjustSelectionRange",
            "AffectedComponent AffectedControl AffectedProperty AlertAsync Alias Alignment All AllCells",
            "AllCellsExceptHeader AllCellsExceptHeaders AllKeys Allow AllowAdd AllowColumnReorder AllowColumnSorting",
            "AllowDrag AllowDrop AllowDuplicateTags AllowedEffect AllowedEffects AllowedFileTypes AllowEdit",
            "AllowedResourceTypes AllowedRoutes AllowEmptyText AllowFolders AllowHtml AllowMarkdown AllowMultipleFiles",
            "AllowNavigation AllowNew AllowRemove AllowSelection AllowSortingDataSource AllowTransparency",
            "AllowUserToAddItems AllowUserToAddRows AllowUserToDeleteItems AllowUserToDeleteRows AllowUserToMoveTabs",
            "AllowUserToOrderColumns AllowUserToResizeColumns AllowUserToResizeRows Alphabetic Alphabetical Alt Alt0 Alt1",
            "Alt2 Alt3 Alt4 Alt5 Alt6 Alt7 Alt8 Alt9 AltBackspace AltDownArrow AltF1 AltF10 AltF11 AltF12 AltF2 AltF3",
            "AltF4 AltF5 AltF6 AltF7 AltF8 AltF9 AltLeftArrow AltRightArrow AltUpArrow Always AlwaysBlink AlwaysUnderline",
            "Anchor Angle AnimationName AnnuallyBoldedDates Anonymous Appearance AppearanceKey Appearances Append",
            "AppendFilter AppendHeader AppendText ApplicationExit ApplicationId ApplicationModal",
            "ApplyCellStyleToEditingControl ApplyCharacterCasing ApplySettings ApplySort ApplyState ApplyStyle",
            "ApplyThemeMixins Apps Arc ArcTo AreAllCellsSelected ArrangeIcons ArrayValue Arrow Ascending AssemblyName",
            "AssignParent AssignTabOrder Attn Auto AutoActivateFirstChild AutoCheck AutoClose AutoCloseDelay",
            "AutoCloseModalDialog AutoCloseModalDialogDefault AutoComplete AutoCompleteList AutoCompleteMode AutoDispose",
            "AutoEllipsis AutoGenerateColumns AutoGenerateColumnsDefault AutoHide AutoHideTaskbar AutoHigh AutoLow",
            "Automatic AutomaticDelay AutoOverflow AutoPlay AutoPopDelay AutoReload AutoResize AutoResizeColumn",
            "AutoResizeColumnHeadersHeight AutoResizeColumns AutoResizeRow AutoResizeRowHeadersWidth AutoResizeRows",
            "AutoScaleDimensions AutoScaleFactor AutoScaleMode AutoScroll AutoScrollMargin AutoScrollMinSize",
            "AutoScrollOffset AutoScrollPosition AutoSelectFirstRow AutoSelectFirstRowDefault AutoShow AutoShowLoader",
            "AutoSize AutoSizeColumnsMode AutoSizeMode AutoSizeRowsMode AutoSizeToAllHeaders AutoSizeToDisplayedHeaders",
            "AutoSizeToFirstHeader AutoToolTip AutoValidate Average Axis B Back BackColor BackgroundImage",
            "BackgroundImageAlign BackgroundImageLayout BackgroundImageSource Backspace BarColor Bday BdayDay BdayMonth",
            "BdayYear BecomingActiveControl Beep Begin BeginBrowserDragDrop BeginDragDrop BeginEdit BeginInit BeginInvoke",
            "BeginPath BeginUpdate Below Best BestFit Bevel BezierCurveTo BinarySearch BinaryWrite BindableComponent",
            "Binding BindingCompleteContext BindingCompleteState BindingContext BindingField BindingMember",
            "BindingMemberInfo BindingPath Bindings BindingSetPropVale BindingSource BindToDataAndErrors Bitmap Blink",
            "BlinkAnimation BlinkIfDifferentError BlinkRate BlinkStyle Blocks BlockSize BoldedDates BorderStyle",
            "BorderStyleBottom BorderStyleLeft BorderStyleRight BorderStyleTop Both Bottom BottomCenter BottomLeft",
            "BottomRight BottomUp Bounce BoundColumnConverter BoundColumnIndex BoundColumnSortOrder BoundColumnValueType",
            "BoundCommandConverter BoundCommandIndex Bounds BringToFront BrowsableAttributes Browser BrowserBack",
            "BrowserCheck BrowserFavorites BrowserForward BrowserHome BrowserRefresh Browsers BrowserSearch BrowserStop",
            "Butt Button Button1 Button2 Button3 ButtonCellTemplate ButtonCount ButtonPosition Buttons ButtonsBackColor",
            "ByKeyboard ByMouse C CacheProvider CalcDockedPadding CalendarDimensions Call CallAsync CallWidget CamelCase",
            "Cancel CancelButton CancelCurrentEdit CancelEdit CancelFullScreen CancelRowEdit CanConvertFrom CanConvertTo",
            "CanExecute CanExecuteCommand CanExtend CanFocus CanSelect CanSelectCell CanSort CanUndo CanUpdate Canvas",
            "Capital Capitalize CapsLock Capture CaptureMode Cascade Categorized CategorizedAlphabetical Category",
            "CausesValidation CcAdditionalName CcCsc CcExp CcExpMonth CcExpYear CcFamilyName CcGivenName CcName CcNumber",
            "CcType Cell CellBorderStyle CellCount CellImage CellImageAlignment CellImageLayout CellImageSource",
            "CellRenderer Cells CellSelect CellStyle CellTemplate CellType CellValue1 CellValue2 Center CenterImage",
            "CenterParent CenterScreen CenterToParent CenterToScreen Change Changed ChangedItem ChangeProfile ChangeType",
            "ChangingItem CharacterCasing CheckAlign CheckAvailability CheckBox Checkbox CheckBoxCellTemplate CheckBoxes",
            "Checked CheckedForeColor CheckedIndices CheckedItems CheckFileExists CheckOnClick CheckParentingCycle",
            "CheckPremiumExtensionLicense CheckServerLicense CheckState CheckStateMember Children ChildRows",
            "ChildRowsInternal Clear ClearChecked ClearCore ClearCreateParams ClearInternal ClearRect ClearSelected",
            "ClearSelection ClearSortedColumnsCache Clickable Clicks ClientArea ClientCertificate ClientColIndex",
            "ClientData ClientEvents ClientId ClientIndex ClientRectangle ClientRowIndex Clients ClientSize Clip",
            "ClipboardCopyMode ClipRectangle Clone CloneMenu CloneProperties Close CloseAllWindows CloseBox Closed",
            "CloseDropDown ClosePath CloseReason CloseWebSocket Closing Collapse CollapseAll CollapseAllGridItems",
            "Collapsed CollapsedBounds CollapsePanel CollapseSide Collapsible Color Colors ColSpan Column ColumnContent",
            "ColumnCount ColumnDataName ColumnHeader ColumnHeadersBorderStyle ColumnHeadersDefaultCellStyle",
            "ColumnHeadersDefaultCellStyleInternal ColumnHeaderSelect ColumnHeadersHeight ColumnHeadersHeightSizeMode",
            "ColumnHeadersVisible ColumnIndex Columns ColumnStyles ComboBoxCellTemplate Command CommandManager",
            "CommandPropertyName CommandSource CommaSeparatedValue CommitEdit CommonAppDataPath CommonAppDataRegistry",
            "CompanyName CompareValue Component ComponentManager components Compress ComputeFlexSizes Config",
            "Configuration ConfirmAsync Contain Container ContainerControl Contains ContainsAudio ContainsData",
            "ContainsFileDropList ContainsFocus ContainsImage ContainsKey ContainsRow ContainsText ContentLength Contents",
            "ContentType Context ContextMenu Continue Continuous Control ControlBox ControlKey Controls ControlUpdate",
            "ControlUpdateMode ConvertFrom ConvertMnemonics ConvertTo ConvertToRealRow ConvertToString",
            "ConvertToStringInternal ConvertToText Cookies CookieStorage Copy CopyFrom CopyTo CopyToClient Count",
            "CountItem CountItemFormat Country CountryName Cover Create CreateApplication CreateBoundDataGridViewColumns",
            "CreateCacheProvider CreateCellEditor CreateCellsInstance CreateColumnsInstance CreateComponent CreateControl",
            "CreateControlsInstance Created CreateDataBoundColumn CreateDataGridViewColumnFromType CreateDirectory",
            "CreateEditingControl CreateFlowLayoutSettings CreateGraphics CreateHandle CreateInstance",
            "CreateItemCollection CreateItemElement CreateLinearGradient CreateNamedColor CreateNewID CreatePattern",
            "CreatePrompt CreateRadialGradient CreateRowsInstance CreateStream CreateSummaryRow CreateUI CreationTime",
            "Critical Cross Crsel Css CssClass CssStyle Ctrl0 Ctrl1 Ctrl2 Ctrl3 Ctrl4 Ctrl5 Ctrl6 Ctrl7 Ctrl8 Ctrl9 CtrlA",
            "CtrlB CtrlC CtrlD CtrlDelete CtrlE CtrlF CtrlF1 CtrlF10 CtrlF11 CtrlF12 CtrlF2 CtrlF3 CtrlF4 CtrlF5 CtrlF6",
            "CtrlF7 CtrlF8 CtrlF9 CtrlG CtrlH CtrlI CtrlInsert CtrlJ CtrlK CtrlL CtrlM CtrlN CtrlO CtrlP CtrlQ CtrlR",
            "CtrlS CtrlShift0 CtrlShift1 CtrlShift2 CtrlShift3 CtrlShift4 CtrlShift5 CtrlShift6 CtrlShift7 CtrlShift8",
            "CtrlShift9 CtrlShiftA CtrlShiftB CtrlShiftC CtrlShiftD CtrlShiftE CtrlShiftF CtrlShiftF1 CtrlShiftF10",
            "CtrlShiftF11 CtrlShiftF12 CtrlShiftF2 CtrlShiftF3 CtrlShiftF4 CtrlShiftF5 CtrlShiftF6 CtrlShiftF7",
            "CtrlShiftF8 CtrlShiftF9 CtrlShiftG CtrlShiftH CtrlShiftI CtrlShiftJ CtrlShiftK CtrlShiftL CtrlShiftM",
            "CtrlShiftN CtrlShiftO CtrlShiftP CtrlShiftQ CtrlShiftR CtrlShiftS CtrlShiftT CtrlShiftU CtrlShiftV",
            "CtrlShiftW CtrlShiftX CtrlShiftY CtrlShiftZ CtrlT CtrlU CtrlV CtrlW CtrlX CtrlY CtrlZ culture Culture",
            "CultureInfo CurrencyManager CurrencyManager_ListChanged CurrencyManager_PositionChanged CurrencySymbol",
            "Current CurrentAutoScaleDimensions CurrentCell CurrentCellAddress CurrentCulture CurrentEvent CurrentItem",
            "CurrentItemIndex CurrentLicense CurrentPassword CurrentProfile CurrentRow CurrentTime CurrentValue",
            "CurrentVirtualCell CurrentVirtualRow Cursor Custom CustomAnimations CustomColors CustomFormat Cut D D0 D1 D2",
            "D3 D4 D5 D6 D7 D8 D9 Dashed Data DataBindings DataBoundItem DataBoundRowsCount DataConnection DataCount",
            "DataError DataFieldIsReadOnly DataGridView DataItem DataManager DataMember DataObject DataPropertyName",
            "DataRead DataReloadThreshold DataRepeaterBindings DataRepeaterItem DataSource DataSource_Initialized",
            "DataSourceNullValue DataSourceUpdate DataSourceUpdateMode Date DateTime DatetimeLocal",
            "DateTimePickerCellTemplate Debug DebugIf DebugMode Decimal DecimalDigits DecimalPlaces Decrement Default",
            "DefaultBackColor DefaultButton1 DefaultButton2 DefaultButton3 DefaultCellStyle DefaultCellStyleInternal",
            "DefaultCursor DefaultDataSourceUpdateMode DefaultExtension DefaultFont DefaultForeColor",
            "DefaultHeaderCellType DefaultItemPadding DefaultLocation DefaultMargin DefaultMaximumSize DefaultMinimumSize",
            "DefaultNamespace DefaultNewRowValue DefaultPadding DefaultPasswordText DefaultProfile DefaultRowHeight",
            "DefaultSize DefaultSortMode DefaultTheme Delay Delete Deleted DeleteDirectory DeleteFile DeleteItem",
            "DeleteRow Delta Depth16Bit Depth24Bit Depth32Bit Depth4Bit Depth8Bit Descending Description DeselectAll",
            "Deselected Deselecting DeselectPanel DeselectTab DesignerTimeout DesignMode DesignRect DesignSkin",
            "DesiredType Desktop DesktopMode DestinationAtop DestinationIn DestinationOut DestinationOver",
            "DestroyComponents DestroyHandle DetachFromDataGridView Details Device DeviceContext DeviceName DeviceRegex",
            "DialogResult DialogTemplate Dib Dif Diff Direct Direction Disable DisableClientObjectModel Disabled",
            "DisabledLinkColor DisableMeasurementsCache DisableMergedMenu DisableMinification DisableResizing",
            "DispatchEvents Display DisplayBoundIndex Displayed DisplayedCells DisplayedCellsExceptHeader DisplayedItems",
            "DisplayIndex Displaying DisplayMember DisplayPropertyName DisplayRectangle Dispose DisposeProperties",
            "Disposing Distance Divide Dock DockPadding DoDragDrop DoLayoutTransaction Domain DoModal",
            "DoNotChangePositionInCurrencyManager DoNotChangePositionInDataGrid Dotted Double DoubleBuffered DoubleClick",
            "Down DownFirst Download DownloadAndOpen DownloadURL DragAction DragDrop DragSource DrawFontSample DrawImage",
            "Drop DropDown DropDownButton DropDownControl DropDownControlAsync DropDownHeight DropDownList DropDownMenu",
            "DropDownStyle DropDownWidth DropDuplicateClicks DropEffect DroppedDown DropSource DropTarget Duration E Ease",
            "EaseIn EaseInOut EaseOut Editable EditedFormattedValue EditingCellAddress EditingControl EditMode",
            "EditOnEnter EditOnF2 EditOnKeystroke EditOnKeystrokeOrF2 Editor EditorInternal EditProgrammatically EditType",
            "EditValue EditValueAsync Effect Element Email Embedded EmbeddedResourcesCacheControl Empty",
            "EnableAllowFocusChange EnableAlwaysIncludeHeaderText EnableChildren Enabled EnabledInternal",
            "EnableNativeContextMenu EnablePreventFocusChange EnablePWA EnableResizing EnableUnloadConfirmation",
            "EnableWebSocket EnableWebSocketCompression EnableWithAutoHeaderText EnableWithoutHeaderText End",
            "EndCurrentEdit EndDragDrop EndEdit EndIndex EndInit EndInvoke EndModal EndPolling EndRequest EndUpdate",
            "EnhancedMetafile EnsureFocusable EnsureProperties EnsureUnvalidatedControl EnsureVisible",
            "EnsureVisibleInternal Enter Environment Equals EqualsFormattedNullValue EraseEof Error ErrorProvider",
            "ErrorText ErrorType Escape EscapePressed EscapeText EscapeTextInternal Eval EvalAsync Event Events ExactFit",
            "Exception Exclamation ExcludeList ExcludePromptAndLiterals ExcludeUnselectedColumns ExcludeUnselectedRows",
            "ExecutablePath Execute ExecuteCommand Exists Exit Expand Expandable ExpandAll ExpandAllGridItems Expanded",
            "Expire Expired Expires Exsel F F1 F10 F11 F12 F13 F14 F15 F16 F17 F18 F19 F2 F20 F21 F22 F23 F24 F3 F4 F5 F6",
            "F7 F8 F9 False FalseValue FamilyName FavIcon FavIconSource Features FileDrop FileName FileNames FilePath",
            "Files FileSize FileSizes FileSystem FileTooLarge Fill FillItems FillRect FillStyle FillText FillWeight",
            "Filter FilterAnywhere FilterAppend FilterExpression FilterIndex FilterItemOnProperty Finalize FinalMode Find",
            "FindAll FindComponent FindComponents FindDesignComponent FindFontFamily FindForm FindIndex FindItem",
            "FindItemWithText FindLast FindLastIndex FindMergePosition FindModalFrameIndex FindPage FindReplacePosition",
            "FindString FindStringExact FireCurrentItemChanged FireListChanged First FirstDayOfWeek FirstDisplayedCell",
            "FirstDisplayedColumnIndex FirstDisplayedItemIndex FirstDisplayedRowIndex FirstIndex FirstItemIndex FirstNode",
            "FirstRow Fixed FixedPanel FixedSize FixedToolWindow FlowDirection Flush Focus Focusable FocusActiveControl",
            "Focused FocusedControl FocusedItem FocusFirstChild Font FontHeight Fonts ForceUnlock ForEach",
            "ForEachResponsiveControl ForeColor Form Format FormatHtmlText FormatInfo FormatObject FormatObjectInternal",
            "FormatPlainText FormatProvider FormatString Formatted FormattedValue FormattedValueChanged",
            "FormattedValueType FormattedValueTypeConverter FormattingApplied FormattingEnabled FormBorderStyle",
            "FormOwnerClosing Friday FromBase64 FromChildHandle FromHandle Frozen FullColumnSelect FullPath FullRowSelect",
            "G GenerateDesignRow Get GetAcceptedEncoding GetAccordionPanelOfComponent GetAlignX GetAlignY GetAnimation",
            "GetAnimationProperties GetAnyDesignModeInHierarchy GetAnyDisposingInHierarchy GetAppearance GetApplicationId",
            "GetAppSwitch GetAssemblyLastWriteTime GetAttribute GetAttributes GetAttributeValue GetAudioStream",
            "GetAutoSizeMode GetAutoValidateForControl GetBackColor GetCantConvertMessage GetCaptionHeight",
            "GetCaptionWidth GetCellDataValue GetCellPosition GetCellSize GetChecked GetCheckState GetChildAtPoint",
            "GetChildIndex GetClientCallback GetClientEventListener GetClipboardContent GetColor GetColorProperty",
            "GetColorStyle GetColumn GetColumnCount GetColumnSpan GetColumnsWidth GetColumnWidths GetCombinedHashCodes",
            "GetCommand GetCommandProperties GetComponent GetComponentResourceUrl GetConfiguration GetContainerControl",
            "GetContentPadding GetContextMenu GetControl GetControlFromPosition GetControlState GetCoreResourceAssemblies",
            "GetCPULoad GetCreated GetCreateInstanceSupported GetCreationTime GetCssClass GetData GetDataObject",
            "GetDataPresent GetDataStoreTarget GetDefaultColor GetDefaultDefaultLayoutEngine GetDefaultFlowLayoutEngine",
            "GetDefaultLayoutEngine GetDefaultLineColor GetDefaultLineSize GetDefaultLineStyle GetDefaultSize",
            "GetDefaultStyle GetDefaultTableLayoutEngine GetDefaultValue GetDesignerHost GetDirectories GetDisplayRange",
            "GetDisplayRectInternal GetDisplayText GetDownloadCallbackId GetEditedFormattedValue",
            "GetEditingControlFormattedValue GetEditStyle GetEnabled GetEntry GetEnumerator GetError GetErrorEntry",
            "GetErrorText GetETag GetEventListEntryHandler GetEventListEntryKey GetEventListEntryNext GetEventsHead",
            "GetField GetFileDropList GetFileIcon GetFileName GetFileResourcePath GetFiles GetFileSize GetFillWeight",
            "GetFirstColumn GetFirstRow GetFirstRowIndex GetFirstSelectedIndex GetFlowBreak GetFont",
            "GetFontAutoScaleDimensions GetFontHeight GetFontProperty GetForm GetFormat GetFormats GetFormattedValue",
            "GetFormatterCulture GetFullPath GetHashCode GetHeight GetHelpTip GetIconAlign GetIconAlignment",
            "GetIconPadding GetImage GetImageBase64 GetImageFormat GetImageList GetImageMediaType GetImageSettings",
            "GetImageSize GetImageUrl GetInheritedContextMenu GetInheritedState GetInheritedStyle GetInsets GetInstance",
            "GetItem GetItemChecked GetItemCheckState GetItemDisplayText GetItemDisplayValue GetItemIcon",
            "GetItemProperties GetItems GetItemText GetItemTextWithoutHtml GetItemToolTip GetItemValue GetJavaScript",
            "GetJavaScriptEvents GetJavaScriptSource GetKey GetKeys GetKeysAsync GetLastColumn GetLastModified GetLastRow",
            "GetLastRowIndex GetLastWriteTime GetLayoutBounds GetLineDash GetList GetListItemProperties GetListItemType",
            "GetListName GetMainAssembly GetMainMenu GetMainMenuHeight GetMargin GetMaxHeight GetMaxWidth GetMdiForms",
            "GetMeasurementSizeFromCache GetMemberInternal GetMemoryUsed GetMenuBar GetMethod GetMethods GetMimeType",
            "GetMinHeight GetMinWidth GetMnemonic GetMnemonicInternal GetMultiple GetNewClientCallbackId",
            "GetNewComponentId GetNewResourceId GetNewSessionId GetNextColumn GetNextControl GetNextRow GetNextRowIndex",
            "GetNodeCount GetNonCoreResourceAssemblies GetOptions GetOriginalFontName GetOutputPath GetPadding",
            "GetPaintValueSupported GetPanel GetPixels GetPlatform GetPositionFromControl GetPostbackURL GetPreferredSize",
            "GetPreviousColumn GetPreviousRow GetPreviousRowIndex GetProperties GetPropertiesSupported GetProperty",
            "GetRealIndex GetRealRow GetRectGroup GetRelatedCurrencyManager GetRequestName GetRequestPath",
            "GetResourceAssemblies GetResourceContent GetResourcePath GetResourceStream GetResourceString GetResourceURL",
            "GetResponsiveAttribute GetRoot GetRootPath GetRotation GetRow GetRowCount GetRowHeights GetRowsHeight",
            "GetRowSpan GetRowState GetScaledBounds GetScriptEntry GetScrollBarSize GetScrollState GetSelected",
            "GetSelectedIndices GetSelectionRanges GetServerVariable GetService GetServicePath GetServiceSessionId",
            "GetServiceURL GetSize GetSortingInformationFromBackend GetSource GetStandardValues GetState GetString",
            "GetStyle GetSvgBase64 GetTabIndex GetTabOrder GetTabPage GetTabPageOfComponent GetTabRect GetTabRectAsync",
            "GetTabStop GetTempFilePath GetTempPath GetText GetTextColor GetTheme GetThemeBackColor GetThemeBarColor",
            "GetThemeColor GetThemeFilePath GetThemeFont GetThemeFontHeight GetThemeForeColor GetThemeImage",
            "GetThemeScrollBarSize GetThemeStateName GetToolTip GetToolTipText GetTopLevel GetValidationRules GetValue",
            "GetVirtualIndex GetVirtualRow GetVisible GetVisibleCore GetWidth GetWisejRequestType GivenName GlobalAlpha",
            "GlobalCompositeOperation GoBack GoForward Google Gpu Grab Graphics GridItem GridItems GridItemType GridLines",
            "GridLineStyle GroupFromColumn GroupRows GroupToColumn GrowAndShrink GrowOnly GrowStyle H Hand Handle",
            "HandleApplicationException Handled HandleInvalidSessionException Hanging HanguelMode HangulMode HanjaMode",
            "HasAnimationProperties HasBindingContext HasCell HasCells HasChildren HasChildRows HasClientEventListener",
            "HasCssClass HasCustomEditor HasDataBindings HasDefaultCellStyle HasDefaultHeaderCellType HasEditor",
            "HasErrorEntry HasErrors HasErrorText Hash HasHandler HasHeaderCell HasHierarchicalRows HasItems HasKeys",
            "HasLayoutBounds HasMdiChildren HasNativeScrollbars HasOverlappedScrollbars HasOwnedForms HasPendingDownloads",
            "HasPendingUpdates HasProperties HasProperty HasResponsiveProfiles HasRowHeight HasScriptEntry",
            "HasSelectedCells HasSize HasState HasStyle HasToolTipText HasUserData HasValue HasValues HasValueType Header",
            "HeaderAlignment HeaderAndColumnContent HeaderBackColor HeaderCell HeaderCellCore HeaderForeColor HeaderImage",
            "HeaderImageSource HeaderPosition Headers HeaderSize HeaderStyle HeaderText Height HeightInternal Help",
            "HelpTipIcon HelpVisible Hexadecimal HHMM HHMMSS Hidden Hide HideBackface HideNodeImage HideNodeImages",
            "HidePromptOnLeave HideTabPage HideUpDownButtons HideValue High HitTest HM HMS Home HonorificPrefix",
            "HonorificSuffix Horizontal HorizontalAlign HorizontalResolution HorizontalScroll HorizontalScrollbar",
            "HorizontalScrollingOffset Hover HoverUnderline HRef HSBToRGB HScroll HSplit Html HtmlSource HttpContext",
            "HttpOnly I IBeam Icon IconAlignment IconBoundIndex IconIndex IconLarge IconLargeSettings IconLargeSource",
            "IconMember IconPadding IconPropertyName IconSettings IconSource Id ID Identifiers Ideographic Ignore",
            "IgnoreDefaults IgnoreNulls Image ImageAboveText ImageAlign ImageAlignment ImageBeforeText ImageCellTemplate",
            "ImageCount ImageFromBase64 ImageIndex ImageIndexer ImageKey ImageLayout ImageList ImagePosition Images",
            "ImageSettings ImageSize ImageSource ImageSpacing IMEAccept IMEAceept IMEConvert ImeMode IMEModeChange",
            "IMENonconvert ImmediateChildren Impersonate Impp Inactive InAddNewRow InBeginEdit InBindingContextChanged",
            "InCellValidating InClientEvent IncludeLiterals IncludePrompt IncludePromptAndLiterals",
            "IncludeSubItemsInSearch InCommitEdit InCommittingNewRow Increment IncrementalSelection InDataFilling",
            "InDataRead Indent Indeterminate IndeterminateValue Index IndexOf IndexOfKey InEditorSetup Info Information",
            "Inherit Inheritable InheritedAutoSizeMode InheritedCellStyle InheritedSortMode InheritedState InheritedStyle",
            "InInitialization InitialDelay InitialDirectory Initialize InitializeAndRegister InitializeComponent",
            "Initialized InitializeEditingControl InitLayout InitScript InitSynchronizationContext InputBox InputBoxAsync",
            "InputStream InputType InRefreshColumns InRowValidating Insert InsertCopies InsertCopy InsertInternal",
            "InsertRange InSetDataConnection Inside InSort Instance InstanceId Instant Integrity InterceptArrowKeys",
            "IntersectSizes Interval Invalid Invalidate InvalidateMeasurementsCache InvalidDomains InvalidEntries",
            "InvalidMessage InvalidSessionHttpCode Invisible Invoke InvokeDownloadCallback InvokeEndResponseCallbacks",
            "InvokeFilter InvokeGotFocus InvokeLostFocus InvokeOnClick InvokePaint InvokePaintBackground InvokeRequired",
            "InvokeStringParseMethod IPAddress IsAccessible IsAlignedBottom IsAlignedCenter IsAlignedLeft IsAlignedMiddle",
            "IsAlignedRight IsAlignedTop IsAllowedResource IsAltPressed IsAuthenticated IsBinding IsBindingSuspended",
            "IsCachedVersionValid IsCellEditable IsCellEmpty IsCellSelected IsCellStyleChanged IsCellVisible IsChild",
            "IsClosed IsCriticalException IsCtrlPressed IsCurrent IsCurrentCell IsCurrentCellDirty",
            "IsCurrentCellInEditMode IsCurrentItemModified IsCurrentRowDirty IsDarkMode IsDataBound",
            "IsDataSourceNullValueDefault IsDefault IsDescendant IsDialog IsDirectory IsDirty IsDisposed",
            "IsDropDownResizable IsEditing IsEmbedded IsEmpty IsEnabled IsEqual IsExpanded IsExpired IsFixedSize",
            "IsFormatProviderDefault IsFullScreen IsHandleCreated IsHeightDynamic IsHorizontal IsHttp IsInEditMode",
            "IsInputChar IsInputKey IsKeyLocked IsKnownType IsLabel IsLoaded IsLocal IsLocked IsMdiChild IsMdiContainer",
            "IsMenuBar IsMirrored IsMixin IsMnemonic IsMultiTouch IsNew IsNewRow IsNullData IsNullValueDefault IsParent",
            "IsPostbackProperty IsPrefixSearch IsReadOnly IsResourceFile IsResponsive IsResponsiveContainer",
            "IsResponsiveProperty IsRightToLeft IsRootNode IsRow IsRowsCollection IsSecure IsSelected IsServerAvailable",
            "IsShiftPressed IsSorted IsSplitterFixed IsSupported IsSynchronized IsTaskbarVisible IsTerminated",
            "IsThemeColor IsThemeFont IsTopLevel IsUpdateSuspended IsUserPaint IsValidCell IsValidClient IsValidColumn",
            "IsValidIndex IsValidInput IsValidRow IsVertical IsVirtual IsVirtualRow IsVisibleRow IsWebMethod IsWebSocket",
            "IsWidthDynamic Item ItemBorderStyle ItemCount ItemDisplaySize ItemHeaderSize ItemHeaderVisible ItemHeight",
            "ItemIndex ItemPadding Items ItemSelectedBackColor ItemSelectedForeColor ItemSize ItemSorter ItemTemplate J",
            "JavaScript JavaScripts JunjaMode K KanaMode KanjiMode Keep KeepAlign KeepAliveInterval KeepCentered",
            "KeepFormatOnEnter KeepOnScreen KeepPosition KeepSameRowHeight KeepWatermark Key Keyboard KeyChar KeyCode",
            "KeyData KeyPreview Keys KeyState KeyValue L Label LabelEdit LabelText LabelWrap Landscape Language",
            "LargeChange LargeIcon LargeImageList LargeImageSettings Last LastIndex LastItemIndex LastModified LastNode",
            "LastRow LastWriteTime LaunchApplication1 LaunchApplication2 LaunchMail Lax Layout LayoutChildren",
            "LayoutEngine LayoutSettings LayoutStyle LazyLoading LButton LControlKey Left LeftBottom LeftMiddle LeftTop",
            "LeftToRight Length Level LicenseAssembly LicenseInfo LicenseKey LicenseManagerTimeout Lighter Linear LineCap",
            "LineColor LineDashOffset LineFeed LineJoin Lines LineSize LineStyle LineTo LineWidth Link LinkArea",
            "LinkBehavior LinkCellTemplate LinkColor List ListChangedType ListItem ListView",
            "ListView_ItemsCollectionChanged ListWasReset LiveResize LiveUpdate LMenu Load LoadAssembly LoadAsync",
            "LoadClientProfiles LoadComponent Loaded Loader LoaderTimeout LoadObjects LoadPackages LoadPackagesAsync",
            "LoadPlatform LoadProperties LoadServerVariables LoadTheme LoadTimeout Locale LocalHost LocalStorage Location",
            "Locations Lock Locked LockKeys LockTimeout Log Long Loop Low Lower LShiftKey LWin M MainMethod MainPage",
            "MainWindow MainWindowType MakeFirstDisplayedCellCurrentCell Manual MapPath MapToDataBoundField",
            "MapToDataBoundFields Margin Marquee Mask MaskedTextBoxCellTemplate MaskedTextProvider MaskText Match",
            "MatchCurrencyManagerPosition Max MaxCachedBlocks MaxCPU MaxDate MaxFileSize MaximizeBox Maximized",
            "MaximizedMargin Maximum MaximumDateTime MaximumHeight MaximumSize MaximumValue MaximumWidth MaxInputLength",
            "MaxLength MaxMeasurementCacheSize MaxMemory MaxModalStack MaxScreenWidth MaxSelectionCount MaxSessions",
            "MaxSessionsPerClient MaxSize MaxTagCount MaxTagWidth MaxWidth MButton MdiChild MdiChildren MdiClient",
            "MdiFormClosing MdiList MdiListItem MdiParent MdiTabProperties MeasureString MeasureStringInternal",
            "MeasureText MeasureTextAsync MediaNextTrack MediaPlayPause MediaPreviousTrack MediaStop Medium Menu MenuBar",
            "MenuID MenuItem MenuItems Merge MergedMenu MergeItems MergeMenu MergeOrder MergeProperties MergeState",
            "MergeStyle MergeType Message MetafilePict MetricsCache Middle MiddleCenter MiddleLeft MiddleRight Min",
            "MinDate MinFieldLength MinificationDisabled MinimizeBox Minimized Minimum MinimumDateTime MinimumHeight",
            "MinimumLength MinimumSize MinimumValue MinimumWidth MinScreenWidth MinSize MinWidth Miter MiterLimit Modal",
            "Mode Modified ModifierKeys Modifiers Monday Month MonthlyBoldedDates MouseButtons MouseCapture MousePosition",
            "Movable Move Moved MoveDown MoveFirst MoveFirstItem MoveLast MoveLastItem MoveNext MoveNextItem MovePrevious",
            "MovePreviousItem MoveTo MoveUp Mozilla MsgBox MsgBoxAsync MsgBoxHelp MsgBoxRight MsgBoxRtlReading",
            "MsgBoxSetForeground MultiExtended Multiline Multiply Multiselect MultiSelect MultiSimple Muted N Name",
            "NameFillWeight Names NameTitle Native Navigate NetworkCheckInterval Never NeverBlink NeverUnderline New",
            "NewDisplayIndex NewFocus NewKey NewPassword NewRowIndex NewSelection NewTabPageIndex NewValue Next NextNode",
            "NextVisibleNode Nickname No NoBorder NoDataMessage Node NodeCount NodeFont Nodes NoName NonClickable None",
            "NoRepeat Normal NoScale NoSelection NoSort NotAllowed NotAvailableUrl Notify NotifyCurrentCellDirty NotSet",
            "NotSortable NotSupportedUrl NullableUnwrap NullableValue NullData NullValue Number Numeric",
            "NumericUpDownCellTemplate NumLock NumPad0 NumPad1 NumPad2 NumPad3 NumPad4 NumPad5 NumPad6 NumPad7 NumPad8",
            "NumPad9 O ObjectEquals ObjectFit Oem1 Oem102 Oem2 Oem3 Oem4 Oem5 Oem6 Oem7 Oem8 OemBackslash OemClear",
            "OemCloseBrackets OemComma OemMinus OemOpenBrackets OemPeriod OemPipe OemPlus OemQuestion OemQuotes",
            "OemSemicolon OemText OemTilde Off OfflineUrl Offset OK Ok OkCancel OKCancel OkOnly OldDisplayIndex OldFocus",
            "OldSelection OldValue On OnAccelerator OnAcceptsTabChanged OnActivated OnAddingNew OnAddReferences",
            "OnAfterCheck OnAfterCollapse OnAfterExpand OnAfterItemCheck OnAfterLabelEdit OnAfterSelect",
            "OnAllowUserToAddItemsChanged OnAllowUserToAddRowsChanged OnAllowUserToDeleteItemsChanged",
            "OnAllowUserToDeleteRowsChanged OnAllowUserToOrderColumnsChanged OnAllowUserToResizeColumnsChanged",
            "OnAllowUserToResizeRowsChanged OnAppear OnAppearanceChanged OnAutoComplete OnAutoGenerateColumnsChanged",
            "OnAutoSizeChanged OnAutoSizingColumnsComplete OnAutoSizingRowsComplete OnAutoValidateChanged",
            "OnBackColorChanged OnBackgroundImageChanged OnBackgroundImageLayoutChanged OnBecomingActiveControlChanged",
            "OnBeforeCheck OnBeforeCollapse OnBeforeExpand OnBeforeLabelEdit OnBeforeSelect OnBindingComplete",
            "OnBindingContextChanged OnButtonClick OnButtonDropDown OnCacheItemRemoved OnCacheVirtualItems",
            "OnCausesValidationChanged OnCellBeginEdit OnCellClick OnCellCommandChanged OnCellCommandNeeded",
            "OnCellCommandPushed OnCellContextMenuNeeded OnCellDoubleClick OnCellEndEdit OnCellEnter",
            "OnCellErrorTextChanged OnCellErrorTextNeeded OnCellFormatting OnCellLeave OnCellMouseClick",
            "OnCellMouseDoubleClick OnCellMouseDown OnCellMouseEnter OnCellMouseLeave OnCellMouseMove OnCellMouseUp",
            "OnCellPaint OnCellParsing OnCellStateChanged OnCellStyleChanged OnCellStyleContentChanged OnCellToolClick",
            "OnCellToolTipTextChanged OnCellToolTipTextNeeded OnCellValidated OnCellValidating OnCellValueChanged",
            "OnCellValueNeeded OnCellValuePushed OnCheckedChanged OnCheckStateChanged OnCheckStateMemberChanged OnClick",
            "OnClientSizeChanged OnClosed OnCloseUp OnClosing OnCollapse OnCollectionChanged OnCollectionChanging",
            "OnColumnAdded OnColumnClick OnColumnDisplayIndexChanged OnColumnDoubleClick OnColumnFillWeightChanged",
            "OnColumnHeaderMouseClick OnColumnHeaderMouseDoubleClick OnColumnHeadersHeightChanged",
            "OnColumnMaximumWidthChanged OnColumnMinimumWidthChanged OnColumnNameChanged OnColumnRemoved",
            "OnColumnReordered OnColumnSortModeChanged OnColumnStateChanged OnColumnWidthChanged OnCommandChanged",
            "OnComponentChanged OnComponentChanging OnContextMenuChanged OnControlAdded OnControlCreated OnControlRemoved",
            "OnCreateControl OnCultureChanged OnCurrentCellChanged OnCurrentChanged OnCurrentItemChanged",
            "OnCurrentItemIndexChanged OnCurrentTimeChanged OnCursorChanged OnCustomFormatChanged OnDataBindingComplete",
            "OnDataCount OnDataError OnDataGridViewChanged OnDataMemberChanged OnDataRead OnDataSourceChanged",
            "OnDataUpdated OnDateChanged OnDateSelected OnDeactivate OnDefaultCellStyleChanged OnDefaultRowHeightChanged",
            "OnDefaultValuesNeeded OnDeselected OnDeselecting OnDisappear OnDisplayMemberChanged OnDisplayRangeChanged",
            "OnDockChanged OnDocumentCompleted OnDoubleClick OnDoWork OnDragDrop OnDragEnd OnDragEnter OnDragLeave",
            "OnDragOver OnDragStart OnDropDown OnDropDownClosed OnDropDownStyleChanged One OnEditableChanged",
            "OnEditingControlShowing OnEditModeChanged OnElementClick OnEnabledChanged OnEnd OnEnded OnEndMove",
            "OnEndResize OnEnter OnError OnErrorChanged OneTimeCode OnEvent OnExit OnFileOk OnFontChanged",
            "OnForeColorChanged OnFormat OnFormatChanged OnFormatInfoChanged OnFormatStringChanged",
            "OnFormattingEnabledChanged OnFormClosed OnFormClosing OnGotFocus OnGroupBoxCollapsed OnGroupBoxExpanded",
            "OnHandleCreated OnHandleDestroyed OnHelpButtonClicked OnHelpRequested OnHRefChanged OnHtmlChanged",
            "OnHtmlSourceChanged OnIconMemberChanged OnImeModeChanged OnInitMenuPopup OnItemCheck OnItemChecked",
            "OnItemClick OnItemCloned OnItemCloning OnItemDoubleClick OnItemDrag OnItemMouseHover OnItemMouseLeave",
            "OnItemsAdded OnItemsCollectionChanged OnItemSelected OnItemSelectionChanged OnItemsRemoved OnItemUpdate",
            "OnItemValueNeeded OnItemValuePushed OnKeepAlive OnKeepSameRowHeightChanged OnKeyDown OnKeyPress OnKeyUp",
            "OnLastCellTab OnLayout OnLayoutStyleChanged OnLeave OnLinkClicked OnListChanged OnLiveResizeChanged OnLoad",
            "OnLoadCompleted OnLoadPath OnLocationChanged OnLongTap OnLostFocus OnMarginChanged OnMaskChanged",
            "OnMaximizedMarginChanged OnMaximumSizeChanged OnMdiChildActivate OnMdiChildAdded OnMdiChildRemoved",
            "OnMenuCollapse OnMenuItemAdded OnMenuItemClicked OnMenuItemRemoved OnMenuPopup OnMethodCall",
            "OnMinimumSizeChanged OnModifiedChanged OnMouseCaptureChanged OnMouseClick OnMouseDoubleClick OnMouseDown",
            "OnMouseEnter OnMouseHover OnMouseLeave OnMouseMove OnMouseUp OnMouseWheel OnMultilineChanged",
            "OnMultiSelectChanged OnNameFillWeightChanged OnNewItemNeeded OnNewRowNeeded OnNodeDrag OnNodeMouseClick",
            "OnNodeMouseDoubleClick OnNodeMouseHover OnNodeMouseLeave OnOrientationChanged OnPaddingChanged OnPaint",
            "OnPanelClick OnPanelCollapsed OnPanelCollectionCleared OnPanelExpanded OnPanelHidden",
            "OnParentBackColorChanged OnParentBackgroundImageChanged OnParentBindingContextChanged OnParentChanged",
            "OnParentCursorChanged OnParentEnabledChanged OnParentFontChanged OnParentForeColorChanged",
            "OnParentRightToLeftChanged OnParentVisibleChanged OnParse OnPaused OnPdfSourceChanged OnPinch OnPlaying",
            "OnPointerOver OnPoll OnPopup OnPositionChanged OnPostback OnPreviewKeyDown OnProgress OnProgressChanged",
            "OnPropertyChanged OnPropertySortChanged OnPropertyValueChanged OnPropertyValueDataError",
            "OnPropertyValueFormatting OnPushedChanged OnQueryContinueDrag OnReadOnlyChanged OnRedraw OnRefresh",
            "OnRefreshItems OnReload OnResize OnResponsiveProfileChanged OnRetrieveVirtualItem OnRightToLeftChanged",
            "OnRightToLeftLayoutChanged OnRotate OnRowCollapsed OnRowCollectionChanged OnRowEnter OnRowErrorTextChanged",
            "OnRowErrorTextNeeded OnRowExpanded OnRowHeaderMouseClick OnRowHeaderMouseDoubleClick",
            "OnRowHeadersWidthChanged OnRowHeightChanged OnRowHeightInfoNeeded OnRowLeave OnRowMaximumHeightChanged",
            "OnRowMinimumHeightChanged OnRowsAdded OnRowsRemoved OnRowStateChanged OnRowValidated OnRowValidating",
            "OnRunWorkerCompleted OnScroll OnScrollAnimationEnd OnScrollStepChanged OnSearchForVirtualItem OnSelect",
            "OnSelected OnSelectedGridItemBeginEdit OnSelectedGridItemChanged OnSelectedGridItemEndEdit",
            "OnSelectedIndexChanged OnSelectedItemChanged OnSelectedObjectsChanged OnSelectedValueChanged OnSelecting",
            "OnSelectionChangeCommitted OnSelectionChanged OnSeparatorCharChanged OnSessionTimeout",
            "OnShowColumnVisibilityMenuChanged OnShown OnSizeChanged OnSizeModeChanged OnSortCompare OnSorted",
            "OnSortedChanged OnSpacingChanged OnSplitterMoved OnSplitterMoving OnStandardReturnChanged",
            "OnStandardTabChanged OnStart OnStartMove OnStartResize OnStyleChanged OnSwfSourceChanged OnSwipe OnTabClosed",
            "OnTabClosing OnTabCollectionCleared OnTabIndexChanged OnTabMoved OnTabPageRemoved OnTabStopChanged",
            "OnTabVisibilityChanged OnTagAdded OnTagClick OnTagDoubleClick OnTagRejected OnTagRemoved OnTagRender",
            "OnTagSelected OnTap OnTaskbarAlignmentChanged OnTaskbarPositionChanged OnTaskbarVisibleChanged",
            "OnTextAlignChanged OnTextChanged OnThreadException OnTick OnToolbarButtonClick OnToolbarButtonDropDown",
            "OnToolClick OnToolTipMemberChanged OnTopLeftHeaderClick OnTouchCancel OnTouchEnd OnTouchMove OnTouchStart",
            "OnTrack OnTypeValidationCompleted OnUploaded OnUploading OnUrlChanged OnUserAddedItems OnUserAddedRow",
            "OnUserDeletedItems OnUserDeletedRow OnUserDeletingItems OnUserDeletingRow OnValidated OnValidating",
            "OnValidation OnValueChanged OnValueMemberChanged OnValueTypeChanged OnVirtualItemsSelectionRangeChanged",
            "OnVirtualModeChanged OnVisibleChanged OnVolumeChanged OnWaiting OnWebDataCount OnWebDataRead OnWebEvent",
            "OnWebPaint OnWebRender OnWebRequest OnWebUpdate OnWidgetEvent OnWindowStateChanged op_Addition op_Equality",
            "op_Implicit op_Inequality op_Subtraction Opacity Opaque OpenedImageIndex OpenedImageKey OpenedImageSettings",
            "Opener OpenFile OpenFileStream OpenForms OpenPages OpenWindow OpenWindows Options Organization",
            "OrganizationTitle Orientation Origin Original OriginalSize OriginalTarget OS Output OutputPath OutputStream",
            "OverlappedScrollbars Overlay OverwritePrompt OwnedForms Owner OwningColumn OwningColumnItems OwningRow P Pa1",
            "Packages Packet Padding PageDown PageInsets PageSource PageUp Painter PaintValue Palette Panel Panel1",
            "Panel1Collapsed Panel1MinSize Panel2 Panel2Collapsed Panel2MinSize PanelCount PanelIndex Panels Parameters",
            "Parent ParentContainer ParentForm ParentPage ParentRow Parse ParseControls ParseDialogResult ParseEditText",
            "ParseFormattedValue ParseInternal ParseObject ParseObjectInternal ParseStyles ParsingApplied Password",
            "PasswordChar Paste Path PathSeparator Pause PdfSource PdfStream PenData Percent PerformClick",
            "PerformContainerValidation PerformControlValidation PerformLayout PerformSelect PerformStep Perspective",
            "Photo PhysicalDimension PixelFormat PixelRatio PlacementModeX PlacementModeY Platform Play PlaysInline",
            "Pointer PointToClient PointToScreen PollingInterval PopModalFrame PopulateChildRows PopulateMdiList",
            "PopulateSelectedCells PopulateSelectedColumns PopulateSelectedRows Position PositionChanging",
            "PositionChangingOutsideDataGridView PositionItem Post PostalCode PosterImage PosterImageSource Postfix",
            "PreferredSize PrefetchItems PreFilterEvent Prefix PrepareEditingControlForEdit PreProcessValue",
            "PreserveDecimal PreserveTime PresetColors PreviousProfile PrevNode PrevVisibleNode Print PrintScreen Prior",
            "Process ProcessChangeValueWebEvent ProcessCmdKey ProcessCurrentTimeWebUpdate ProcessDialogChar",
            "ProcessDialogKey ProcessDragDropWebEvents ProcessFileNames ProcessHttpRequest ProcessingMetaDataChanges",
            "ProcessItemCheckChangedWebEvent ProcessKey ProcessKeyboardWebEvents ProcessKeyPreview ProcessMouseWebEvents",
            "ProcessNativeDragDropWebEvents ProcessRequest ProcessResponse ProcessScrollEvent ProcessSplitterMoveWebEvent",
            "ProcessVolumeWebUpdate ProcessWebSocketRequest ProcessWisejRequest ProductName ProductVersion Programmatic",
            "ProjectPath PromptAsync PromptChar PromptFileCreate PromptFileNotFound PromptFileOverwrite Properties",
            "PropertiesAreEqual Property PropertyDescriptor PropertyGrid PropertyName PropertyPath PropertySort Provider",
            "PushButton Pushed PushModalFrame PushValue Q QuadraticCurveTo Quality QueryString Question QXDesktop R Radio",
            "RadioCheck Radius Raise RaiseActiveWindowChanged RaiseApplicationException RaiseApplicationExit",
            "RaiseApplicationRefresh RaiseApplicationStart RaiseBeforeInstallPrompt RaiseBeginRequest",
            "RaiseBrowserSizeChanged RaiseBrowserTabActivated RaiseBrowserTabDeactivated RaiseCanExecuteChanged",
            "RaiseCellClick RaiseCellCommandChanged RaiseCellValueChanged RaiseCultureChanged RaiseDataError",
            "RaiseEndRequest RaiseEnterThreadModal RaiseFocusedControlChanged RaiseHashChanged RaiseIdle",
            "RaiseLeaveThreadModal RaiseLicenseError RaiseListChangedEvents RaisePropertyChanged",
            "RaiseResponsiveProfileChanged RaiseRightToLeftChanged RaiseSessionTimeout RaiseThemeChanged RaiseThreadBegin",
            "RaiseThreadEnd RaiseThreadException Range RawFormat RButton RControlKey ReadOnly ReadSessionId ReadValue",
            "ReadValues Recreate RecreateNewRow RecreatingHandle Rect RectangleToClient RectangleToScreen Redirect",
            "Reference Referrer Refresh RefreshAll RefreshCommands RefreshDesignerSelection RefreshId RefreshItem",
            "RefreshItems RefreshItemsCore RefreshSessionId RefreshValueOnChange Register RegisterClientCallback",
            "RegisterClientFunction RegisterClientScript RegisterEndResponseCallback RegisterResponsiveProfileChanged",
            "RegisterWebMethods RejectInputOnFirstFailure RelatedImageList RelatedImageSettings Reload Remove RemoveAll",
            "RemoveAllAnnuallyBoldedDates RemoveAllBoldedDates RemoveAllMonthlyBoldedDates RemoveAnnuallyBoldedDate",
            "RemoveAt RemoveAtInternal RemoveBoldedDate RemoveByKey RemoveClientEventListener RemoveComponent RemoveCore",
            "RemoveCssClass RemoveCurrent Removed RemoveDeletedItems RemoveDownloadCallbacks RemoveEventFilter",
            "RemoveFilter RemoveFromControls RemoveHandler RemoveInternal RemoveListener RemoveMdiListItems",
            "RemoveMonthlyBoldedDate RemoveOwnedForm RemoveProperty RemoveRange RemoveSort RemoveState RemoveSummaryRows",
            "RemoveValue RemoveWeakHandler Rename RenameDirectory RenameFile Render RenderAppState RenderCheckState",
            "RenderChildren RenderClientScripts RenderComponent RenderComponents RenderDesignMode RenderHeaderCellStyle",
            "RenderImage RenderItem RenderItems RenderMainMenu RenderPanelProperties RenderReferenced",
            "RenderScrollableProperties RenderSelected RenderStyle RenderText RenderWidgetProperties Repeat RepeatX",
            "RepeatY Replace ReplaceSettingsValue Request RequestFullScreen RequestType Required Reset ResetAllowNew",
            "ResetAnimation ResetBackColor ResetBindings ResetCurrentItem ResetCursor ResetDataConnectionState",
            "ResetDefaultValue ResetEnabled ResetFont ResetFontHeight ResetForeColor ResetHeight ResetImage",
            "ResetImageSource ResetImeMode ResetInputType ResetItem ResetItemBorderStyle ResetItemHeaderSize",
            "ResetItemHeaderVisible ResetReadOnly ResetRightToLeft ResetRotation ResetSelectedProperty ResetSize",
            "ResetSplitterWidth ResetTabOrder ResetText ResetThreadAbort ResetValidationRules ResetValue ResetWidth",
            "Resizable ResizableEdges ResizableSet ResolveColor ResolveFont ResolveMainMethod ResolveMainWindowType",
            "Response ResponseHeader ResponseManager ResponseTimeout ResponsiveProfiles Restart Restore RestoreBounds",
            "RestoreSession ResumeBinding ResumeLayout Retry RetryAfter RetryCancel Return ReturnCode",
            "ReturnComponentResource ReturnFile ReturnFileResource ReturnUrl ReturnValue Reverse RGBToHSB Riff Right",
            "RightBottom RightClickSelection RightMiddle RightToLeft RightToLeftInternal RightToLeftLayout RightTop RMenu",
            "Role Root RootName RootPath RootRow Roots Rotate RotateX RotateY RotateZ Rotation Round Row",
            "RowColumnHeaderSelect RowCount RowEditInitialized RowHeader RowHeaderColumn RowHeadersDefaultCellStyle",
            "RowHeadersDefaultCellStyleInternal RowHeaderSelect RowHeadersMaximumWidth RowHeadersMinimumWidth",
            "RowHeadersVisible RowHeadersWidth RowHeadersWidthSizeMode RowHeight RowIndex RowIndex1 RowIndex2",
            "RowIndexOffset Rows RowSpan RowStyles RowTemplate RShiftKey Rtf Rules Run RunInContext RuntimeMode RWin S",
            "SafeFileName SafeFileNames SameDomain SameSite Saturday Save SaveAs SaveWisejScripts SaveWisejStyleSheets",
            "Scale ScaleChildren ScaleControl ScaleCore ScaleDown ScaleMode ScaleSize ScaleX ScaleY ScaleZ Scope",
            "ScreenSize ScriptAccess Scroll Scrollable ScrollAlwaysVisible ScrollBars ScrollBarsEnabled ScrollBarSize",
            "ScrollBarVisible ScrollBy ScrollCellIntoView ScrollColumnIntoView ScrollControlIntoView ScrollItemIntoView",
            "ScrollOrientation ScrollRowIntoView ScrollStep ScrollTo ScrollToX ScrollToY Search Secure Select Selectable",
            "SelectAll SelectAllCells SelectAllColumns SelectAllRows SelectCell Selected SelectedCells SelectedColumns",
            "SelectedGridItem SelectedImageIndex SelectedImageKey SelectedImageSettings SelectedIndex",
            "SelectedIndexInternal SelectedIndices SelectedItem SelectedItems SelectedNode SelectedNodes SelectedObject",
            "SelectedObjects SelectedOnTop SelectedPanel SelectedPath SelectedRows SelectedTab SelectedText SelectedValue",
            "Selecting SelectionDelay SelectionEnd SelectionLength SelectionMode SelectionRange SelectionStart",
            "SelectMedia SelectNextControl SelectOnEnter SelectPanel SelectTab SelectTag SelfSize SelfSizeDefault",
            "SendHttpResponse SendNotModifiedResponse SendResponse SendToBack SendWebSocketResponse",
            "SendWebSocketResponseBrotli SendWebSocketResponseGZip Separator SeparatorChar Serialize SerializeInternal",
            "ServerName ServerPort ServerVariables Service Services ServiceScope Session SessionCount SessionId",
            "SessionStorage SessionTimeout Set SetActiveControl SetAlignX SetAlignY SetAnimation SetAudio",
            "SetAutoScrollMargin SetAutoSizeMode SetBounds SetBoundsCore SetCalendarDimensions SetCellPosition",
            "SetCheckState SetChildIndex SetClientSize SetClientSizeCore SetClientText SetColumn SetColumnIndex",
            "SetColumnSpan SetCommand SetControlState SetCreated SetCssClass SetCurrentCell SetCurrentCellAddressCore",
            "SetData SetDataConnection SetDataObject SetDate SetDefaultValue SetDesignMetrics SetDirty",
            "SetDisplayRectangleSize SetDisplayRectLocation SetDisposed SetDisposing SetDownloadURL SetEnabled SetError",
            "SetFileDropList SetFillWeight SetFlowBreak SetFocusInternal SetHelpTip SetIconAlignment SetIconPadding",
            "SetImage SetItem SetItemChecked SetItemCheckState SetItemCore SetItemsCore SetJavaScript SetJavaScriptSource",
            "SetKeyName SetLayoutBounds SetLineDash SetLockedByOS SetMemberInternal SetMimeType SetNoZOrder",
            "SetOriginalFontName SetParent SetRange SetRotation SetRow SetRowSpan SetRowState SetRowStateInternal",
            "SetScrollState SetSelected SetSelectedCell SetSelectionRange SetSelectionRanges",
            "SetSelfAutoSizeInDefaultLayout SetSessionTimeout SetSortColumn SetStyle SetTabIndex SetTabOrder SetTabStop",
            "SetText SetTimeout Settings SetToolTip SetTopLevel SetTransform SetValidationRules SetValue SetValueInternal",
            "SetValues SetVisible SetVisibleCore SetVisibleScrollbars Sex ShadowBlur ShadowColor ShadowOffsetX",
            "ShadowOffsetY Shift ShiftDelete ShiftF1 ShiftF10 ShiftF11 ShiftF12 ShiftF2 ShiftF3 ShiftF4 ShiftF5 ShiftF6",
            "ShiftF7 ShiftF8 ShiftF9 ShiftInsert ShiftKey Short Shortcut ShouldAutoValidate ShouldBind",
            "ShouldChangeDataMember ShouldPerformContainerValidation ShouldSerializeDefaultCellStyle",
            "ShouldSerializeDefaultValue ShouldSerializeImage ShouldSerializeImageSource ShouldSerializeProfile",
            "ShouldSerializeValue ShouldUpdate Show ShowAll ShowAsync ShowCalendar ShowCellErrors ShowCellToolTips",
            "ShowCheckBox ShowCloseButton ShowColumnVisibilityMenu ShowConsole ShowControls ShowDialog ShowDialogAsync",
            "ShowExpandButton ShowFocusCell ShowHeader ShowHelp ShowHelpToolTips ShowInTaskbar ShowInVisibilityMenu",
            "ShowItemToolTips ShowLoader ShowLoaderInternal ShowMask ShowMdiChildMenu ShowMenu ShowModalMask",
            "ShowNodeToolTips ShowOtherMonth ShowPanels ShowPlusMinus ShowPopup ShowPopupAsync ShowRootLines",
            "ShowRowErrors ShowShortcut ShowTabPage ShowThumbnails ShowToday ShowToolTips ShowUpDown ShowValue",
            "ShowVisibilityMenu ShowWeekNumbers Simple Site Sizable SizableToolWindow Size SizeAll SizeFromClientSize",
            "SizeMode SizeNE SizeNESW SizeNS SizeNW SizeNWSE SizeSE SizeSW SizeType SizeWE SizingGrip SkipServer Sleep",
            "SmallChange SmallIcon SmallImageList SmallImageSettings Smooth Snapshot Solid Sort Sortable",
            "SortByDisplayIndex SortDescriptions SortDirection Sorted SortedColumn SortFrozenRows SortGlyph",
            "SortGlyphDirection Sorting SortItems SortMode SortNodes SortOrder SortProperty SortResult SortSelectionMode",
            "Source SourceAtop SourceComponent SourceControl SourceIn SourceOut SourceOver SourceProperties",
            "SourceProperty SourceURL Space Spacing SpellCheck SplitterDistance SplitterRectangle SplitterWidth SplitX",
            "SplitY Spring Square StandardReturn StandardTab Start StartIndex StartPolling StartPosition StartTask",
            "StartTime StartTimer StartUp StartupPath StartupUri StartupUrl State StateChanged StateExcludes",
            "StateImageIndex StateImageKey StateImageList StateImageSettings StateImageSource StateIncludes StateInternal",
            "States StatusBarPanel StatusCode StatusDescription Std Step Stop StreetAddress Stretch StretchImage Strict",
            "StringFormat Stroke StrokeRect StrokeStyle StrokeText Style StyleInternal Styles Stylesheet StyleSheets",
            "StyleSheetSource SubItems Subtract Success Suggest SuggestAppend Sum SummaryPosition Sunday",
            "SupportsAdvancedSorting SupportsChangeNotification SupportsFiltering SupportsSearching SupportsSorting",
            "SupportsWebSocket SupportsWebSocketCompression SuppressCache SuspendBinding SuspendLayout",
            "SuspendSelectionChange SvgRenderer SwfSource Switch SymbolicLink SyncLock SyncRoot SystemDefault SystemModal",
            "T Tab TabBackColor TabControl TabCount TabForeColor TabId TabIndex TabPage TabPageIndex TabPages TabStop",
            "Tada Tag TagCount Target TaskbarAlignment TaskbarPosition TaskbarSize Tel TelAreaCode TelCountryCode",
            "TelExtension TelLocal TelLocalPrefix TelLocalSuffix TelNational TempPath Terminated Text TextAboveImage",
            "TextAlign TextBaseline TextBeforeImage TextBoxCellTemplate TextFont TextImageRelation TextInternal",
            "TextLength TextMaskFormat TheApp Theme ThemeName ThemesPath ThemeSplitterSize ThousandsSeparator ThreadAbort",
            "ThreadPool ThreeState ThrowException Thursday TickFrequency TickStyle Tiff Tile TileHorizontal TileVertical",
            "Time Timestamp TimezoneId TimezoneInfo TimezoneOffset Timing Title ToArray ToASCII ToBase64 ToClientIndex",
            "TodayDate TodayFormat Toggle ToggleButton ToJSON Tool ToolBar ToolbarVisible Tools ToolsBounds ToolsPosition",
            "ToolTipIcon ToolTipIconSource ToolTipMember ToolTipText Top TopCenter TopDown TopIndex TopLeft TopLeftHeader",
            "TopLeftHeaderCell TopLevel TopLevelControl TopMost TopNode TopRight ToRealIndex ToServerString ToString",
            "Total TotalBytes ToUTF8 TransactionAmount TransactionCurrency Transform Translate TranslateAlignment",
            "TranslateColor TranslateFont TranslateImage TranslateResizableEdges TranslateShortcut TransmitFile",
            "TransmitImage TransmitStream Transparent TransparentColor TransparentImage TreeColumn TreeView",
            "TreeViewNodeSorter Trim TrimExcess True TrueValue TryAssemblyForRootNamespace TryGetMember TryGetValue",
            "TryInvokeMember TryLock TryLookupDisplayValue TryLookupValue TrySetMember Tuesday Type U Unchecked",
            "Underneath UnicodeText UnionSizes Unknown Unlock UnmaskText Unregister UnregisterClientScripts",
            "UnregisterResponsiveProfileChanged Unspecified UnwireEvents Up Update UpdateAccordion UpdateAppState",
            "UpdateBinding UpdateBindings UpdateBounds UpdateCellValue UpdateComponent UpdateControls UpdateEditText",
            "UpdateFocusedControl UpdateIndexes UpdateMdiList UpdateMetrics UpdatePanelSelection UpdatePosition",
            "UpdateResponsiveProfile UpdateSortColumn UpdateSplitContainer UpdateSplitPanels UpdateState UpdateStyles",
            "UpdateTabButtonRect UpdateTabButtonSize UpdateTabOrder UpdateTabSelection UpdateThreadCulture UpdateValues",
            "UpdateWebSocketAuthentication UpdateWidget UpdateZOrder UpDownAlign Upload UploadFiles Upper Uri Url",
            "UrlReferrer UseColumnTextForButtonValue UseColumnTextForLinkValue UseMnemonic UseOptionsAttribute",
            "UseOwningColumnItems User UserAgent UserAgentRegex UserClosing UserData UserHostAddress UserHostName",
            "UserLanguages Username UserPaint UseWaitCursor UseWisej V Validate ValidateActiveControl ValidateApplication",
            "ValidateChildren ValidateClient ValidateEditText ValidateExpression ValidateRequest ValidateResources",
            "ValidateText ValidatingType ValidationCancelled ValidDomains Value ValueMember Values ValueTitle ValueType",
            "ValueTypeConverter Variables Velocity Version Vertical VerticalAlign VerticalResolution VerticalScroll View",
            "ViewerType ViewerURL Virtual VirtualListSize VirtualMode VirtualNode VirtualScroll VisibilityChanged Visible",
            "VisibleCount VisibleInternal VisibleRowCount Visited Volume VolumeDown VolumeMute VolumeUp VScroll VSplit W",
            "WaitCursor Wallpaper WantRowEvents Warning Watermark WaveAudio WeakEvents WebSocket",
            "WebSocketCompressionThreshold Wednesday Week Wheel WheelDelta Width WidthInternal Window WindowMode",
            "WindowState WiredEvents WireEvents WireWebEvents WordWrap WorkingArea Wrap WrapContents WrapMode Write",
            "WriteFile WriteImage WriteStream WriteValue WriteValues X XButton1 XButton2 Xor Y Yes YesNo YesNoCancel Z",
            "Zoom ZoomIn ZoomOut",
        };

        // ── documented type names ───────────────────────────────────────────────────────────────────────
        private static readonly string[] TypeNames =
        {
            "AcceleratorEventArgs AcceleratorEventHandler Accordion AccordionAction AccordionCancelEventArgs",
            "AccordionCancelEventHandler AccordionEventArgs AccordionEventHandler AccordionPageImageProperties",
            "AccordionPanel AccordionPanelControlCollection ActionType AlertBox AnchorStyles Animation AnimationEventArgs",
            "AnimationEventHandler AnimationTiming Appearance Application AspNetPanel AspNetPanelExtensions Audio",
            "AutoComplete AutoCompleteMode AutoScaleMode AutoSizeMode AutoValidate BackgroundWorker BaseCollection",
            "BeginInvokeResult BindableComponent Binding BindingCompleteContext BindingCompleteEventArgs",
            "BindingCompleteEventHandler BindingCompleteState BindingContext BindingExtensions BindingManagerBase",
            "BindingManagerDataErrorEventArgs BindingManagerDataErrorEventHandler BindingMemberInfo BindingNavigator",
            "BindingsCollection BindingSource BitState32 BitState64 Border BorderStyle BoundsSpecified Brotli",
            "BrowserStorage Button ButtonBase ButtonExtensions Cache CacheVirtualItemsEventArgs",
            "CacheVirtualItemsEventHandler Canvas CanvasCompositeOperation CanvasLineCap CanvasLineJoin",
            "CanvasRepeatPattern CanvasTextAlign CanvasTextBaseline CaptureMode CategoryGridItem CharacterCasing CheckBox",
            "CheckedIndexCollection CheckedListBox CheckedListBoxExtensions CheckedListViewItemCollection CheckedMenuItem",
            "CheckedObjectCollection CheckState CheckStateConverter Client ClientBrowser ClientCollection ClientEvent",
            "ClientEventCollection ClientPlatform ClientProfile ClientTheme ClientThemeReader Clipboard CloseProxy",
            "CloseReason ColorDepth ColorDialog ColorDialogUI ColorEditor ColumnClickEventArgs ColumnClickEventHandler",
            "ColumnHeader ColumnHeaderAutoResizeStyle ColumnHeaderCollection ColumnHeaderImageProperties",
            "ColumnHeaderStyle ColumnReorderedEventArgs ColumnReorderedEventHandler ColumnStyle ColumnStyleProxy",
            "ColumnWidthChangedEventArgs ColumnWidthChangedEventHandler ComboBox ComboBoxExtensions ComboBoxStyle Command",
            "CommandArgs CommandManager CommandPropertyDescriptor CommonDialog Component ComponentManager ComponentTool",
            "ComponentToolCollection CompRef CompRefArray Configuration ContainerControl ContextMenu ContextMenuConverter",
            "Control ControlBase ControlBindingsCollection ControlCollection ControlEventArgs ControlEventHandler",
            "ControlExtensions ControlStyles ControlUpdateMode ConvertEventArgs ConvertEventHandler Cookie",
            "CookieCollection CookieStorage CurrencyManager CurrencyValidationRule Cursor CursorConverter Cursors",
            "CustomSummary DataDataManager DataFormats DataGridView DataGridViewAutoSizeColumnMode",
            "DataGridViewAutoSizeColumnsMode DataGridViewAutoSizeRowMode DataGridViewAutoSizeRowsMode DataGridViewBand",
            "DataGridViewBindingCompleteEventArgs DataGridViewBindingCompleteEventHandler DataGridViewButtonCell",
            "DataGridViewButtonColumn DataGridViewCell DataGridViewCellBorderStyle DataGridViewCellCancelEventArgs",
            "DataGridViewCellCancelEventHandler DataGridViewCellCollection DataGridViewCellCommandEventArgs",
            "DataGridViewCellCommandEventHandler DataGridViewCellContextMenuNeededEventArgs",
            "DataGridViewCellContextMenuNeededEventHandler DataGridViewCellErrorTextNeededEventArgs",
            "DataGridViewCellErrorTextNeededEventHandler DataGridViewCellEventArgs DataGridViewCellEventHandler",
            "DataGridViewCellFormattingEventArgs DataGridViewCellFormattingEventHandler DataGridViewCellMouseEventArgs",
            "DataGridViewCellMouseEventHandler DataGridViewCellPaintEventArgs DataGridViewCellPaintEventHandler",
            "DataGridViewCellParsingEventArgs DataGridViewCellParsingEventHandler DataGridViewCellStateChangedEventArgs",
            "DataGridViewCellStateChangedEventHandler DataGridViewCellStyle DataGridViewCellStyleContentChangedEventArgs",
            "DataGridViewCellStyleContentChangedEventHandler DataGridViewCellStyleConverter DataGridViewCellStyleScopes",
            "DataGridViewCellToolTipTextNeededEventArgs DataGridViewCellToolTipTextNeededEventHandler",
            "DataGridViewCellValidatingEventArgs DataGridViewCellValidatingEventHandler DataGridViewCellValueEventArgs",
            "DataGridViewCellValueEventHandler DataGridViewCheckBoxCell DataGridViewCheckBoxColumn",
            "DataGridViewChildRowCollection DataGridViewClipboardCopyMode DataGridViewCollectionChangeEventArgs",
            "DataGridViewColumn DataGridViewColumnCollection DataGridViewColumnConverter DataGridViewColumnEventArgs",
            "DataGridViewColumnEventHandler DataGridViewColumnHeaderCell DataGridViewColumnHeadersHeightSizeMode",
            "DataGridViewColumnSortMode DataGridViewColumnsSortMode DataGridViewColumnStateChangedEventArgs",
            "DataGridViewColumnStateChangedEventHandler DataGridViewComboBoxCell DataGridViewComboBoxColumn",
            "DataGridViewComboBoxEditingControl DataGridViewContentAlignment DataGridViewDataConnection",
            "DataGridViewDataErrorEventArgs DataGridViewDataErrorEventHandler DataGridViewDataReadEventArgs",
            "DataGridViewDataReadEventHandler DataGridViewDataStore DataGridViewDataUpdatedEventArgs",
            "DataGridViewDataUpdatedEventHandler DataGridViewDateTimePickerCell DataGridViewDateTimePickerColumn",
            "DataGridViewDateTimePickerEditingControl DataGridViewEditingControlExtensions",
            "DataGridViewEditingControlShowingEventArgs DataGridViewEditingControlShowingEventHandler",
            "DataGridViewEditMode DataGridViewElement DataGridViewElementStates DataGridViewHeaderCell",
            "DataGridViewImageCell DataGridViewImageCellLayout DataGridViewImageColumn DataGridViewLinkCell",
            "DataGridViewLinkColumn DataGridViewMaskedTextBoxCell DataGridViewMaskedTextBoxColumn",
            "DataGridViewMaskedTextBoxEditingControl DataGridViewNumericUpDownCell DataGridViewNumericUpDownColumn",
            "DataGridViewNumericUpDownEditingControl DataGridViewRow DataGridViewRowCancelEventArgs",
            "DataGridViewRowCancelEventHandler DataGridViewRowCollection DataGridViewRowConverter",
            "DataGridViewRowErrorTextNeededEventArgs DataGridViewRowErrorTextNeededEventHandler DataGridViewRowEventArgs",
            "DataGridViewRowEventHandler DataGridViewRowHeaderCell DataGridViewRowHeaderColumn",
            "DataGridViewRowHeadersWidthSizeMode DataGridViewRowHeightInfoNeededEventArgs",
            "DataGridViewRowHeightInfoNeededEventHandler DataGridViewRowsAddedEventArgs DataGridViewRowsAddedEventHandler",
            "DataGridViewRowsRemovedEventArgs DataGridViewRowsRemovedEventHandler DataGridViewRowStateChangedEventArgs",
            "DataGridViewRowStateChangedEventHandler DataGridViewSelectedCellCollection",
            "DataGridViewSelectedColumnCollection DataGridViewSelectedRowCollection DataGridViewSelectionMode",
            "DataGridViewSortCompareEventArgs DataGridViewSortCompareEventHandler DataGridViewSortSelectionMode",
            "DataGridViewSummaryRow DataGridViewTextBoxCell DataGridViewTextBoxColumn DataGridViewTextBoxEditingControl",
            "DataGridViewTextBoxMultilineEditingControl DataGridViewToolClickEventArgs DataGridViewToolClickEventHandler",
            "DataGridViewTriState DataGridViewVirtualComboBoxEditingControl DataItem DataObject DataRepeater",
            "DataRepeaterAddRemoveItemsCancelEventArgs DataRepeaterAddRemoveItemsCancelEventHandler",
            "DataRepeaterAddRemoveItemsEventArgs DataRepeaterAddRemoveItemsEventHandler DataRepeaterDataErrorEventArgs",
            "DataRepeaterDataErrorEventHandler DataRepeaterItem DataRepeaterItemCloneEventArgs",
            "DataRepeaterItemCloneEventHandler DataRepeaterItemEventArgs DataRepeaterItemEventHandler",
            "DataRepeaterItemValueEventArgs DataRepeaterItemValueEventHandler DataRepeaterLayoutStyles",
            "DataSourceUpdateMode DateRangeEventArgs DateRangeEventHandler DateTimePicker DateTimePickerExtensions",
            "DateTimePickerFormat Day DecimalValidationRule DefaultLayoutEngine DepthLimitedQuickSort Desktop",
            "DesktopTaskBarItem DesktopTaskBarItemClickEventArgs DesktopTaskBarItemClickEventHandler",
            "DesktopTaskBarItemCollection DesktopTaskBarItemControl DesktopTaskBarItemDateTime DialogResult Display",
            "DockPaddingEdges DockPaddingEdgesConverter DockStyle DomainUpDown DomainUpDownItemCollection DragAction",
            "DragDrop DragDropEffects DragEventArgs DragEventHandler DynamicObject DynamicObjectConverter",
            "DynamicPropertyDescriptor Element EmailValidationRule EncodingType Entry ErrorAnimationType ErrorBlinkStyle",
            "ErrorIconAlignment ErrorProvider ErrorProviderErrorChangedEventArgs ErrorProviderErrorChangedHandler",
            "ExtendedPropertyDescriptor ExtendedPropertyValue Extensions FileDialog FileDialogLoadPathEventArgs",
            "FileDialogLoadPathEventHandler FileDialogRootCollection FileDialogUI FileSystemProvider FixedPanel",
            "FlashPlayer FlashPlayerQuality FlashPlayerScale FlashPlayerScriptAccess FlashPlayerWindowMode",
            "FlexLayoutPanel FlexLayoutPanelExtensions FlexLayoutStyle FlowDirection FlowLayoutEngine FlowLayoutPanel",
            "FlowLayoutPanelExtensions FlowLayoutSettings FocusEventArgs FocusEventHandler FolderBrowserDialog",
            "FolderBrowserDialogUI FontNameEditor Form Format Formatter FormBorderStyle FormClosedEventArgs",
            "FormClosedEventHandler FormClosingEventArgs FormClosingEventHandler FormCollection FormExtensions",
            "FormImageProperties FormStartPosition FormWindowState GetChildAtPointSkip GridItem GridItemCollection",
            "GridItemType GridLineStyle GroupBox GroupBoxExtensions HashChangedEventArgs HashChangedEventHandler",
            "HBoxLayoutEngine HeaderPosition HealthCheck HelpEventArgs HelpEventHandler HelpTip HitTestInfo HitTestType",
            "HorizontalAlignment HScrollBar HScrollProperties HtmlPanel HtmlPanelElementClickArgs",
            "HtmlPanelElementClickHandler Http HttpContext HttpCookie HttpCookieCollection HttpFileCollection HttpHandler",
            "HttpPostedFile HttpRequest HttpResponse IBindableComponent IBinding IButtonControl IButtonControlExtensions",
            "ICommand ICommandSource ICommandSourceExtensions IContainerControl ICurrencyManagerProvider",
            "IDataGridViewEditingControl IDataManager IDataObject IDropTarget IErrorProvider IErrorProviderExtensions",
            "IEventFilter IFileSystemProvider IFramePanel IHasPropertyStore IHasResponsiveProfiles IImage",
            "IImageExtensions ILabel ILabelExtensions ImageCellConverter ImageCollection ImageColumnHeader ImageEditor",
            "ImageIndexConverter ImageKeyConverter ImageLayout ImageList ImageListConverter ImageListEntry",
            "ImageListEntryConverter ImagePosition ImagePropertySettings ImageSourceConverter ImeMode IModified",
            "IModifiedExtensions Indexer InitPayload InputType InputTypeConverter IntegerValidationRule Interaction",
            "IReadOnly IReadOnlyExtensions ItemChangedEventArgs ItemChangedEventHandler ItemCheckedEventArgs",
            "ItemCheckedEventHandler ItemCheckEventArgs ItemCheckEventHandler ItemClickEventArgs ItemClickEventHandler",
            "ItemDragEventArgs ItemDragEventHandler ItemMouseHoverEventArgs ItemMouseHoverEventHandler",
            "ItemSelectionChangedEventArgs ItemSelectionChangedEventHandler IUserData IValidation IWisejCacheProvider",
            "IWisejComponent IWisejControl IWisejDataStore IWisejEditorService IWisejExtenderProvider IWisejHandler",
            "IWisejHandlerExtension IWisejSerializable IWisejSynchronized IWisejSynchronizedImplementation IWisejWindow",
            "JavaScript JsonWriter KeyboardInfo KeyEventArgs KeyEventHandler KeyPressEventArgs KeyPressEventHandler Keys",
            "KeysConverter Label LabelEditEventArgs LabelEditEventHandler LabelExtensions LabelPosition",
            "LabelPropertyConverter LabelWrapper LambdaUtils LayoutEngine LayoutEventArgs LayoutEventHandler",
            "LeftRightAlignment LicenseErrorEventArgs LicenseErrorEventHandler Line LineExtensions LineStyle LinkArea",
            "LinkAreaConverter LinkBehavior LinkLabel LinkLabelExtensions LinkLabelLinkClickedEventArgs",
            "LinkLabelLinkClickedEventHandler LinkMenuItem LinkState ListBindingConverter ListBindingHelper ListBox",
            "ListBoxExtensions ListControl ListControlConvertEventArgs ListControlConvertEventHandler",
            "ListControlExtensions ListView ListViewBindingCompleteEventArgs ListViewBindingCompleteEventEventHandler",
            "ListViewComboBox ListViewDataStore ListViewDataUpdatedEventArgs ListViewDataUpdatedEventHandler ListViewItem",
            "ListViewItemCollection ListViewItemConverter ListViewItemDragEventArgs ListViewItemDragEventHandler",
            "ListViewItemImageProperties ListViewItemStateImageProperties ListViewItemStates ListViewSubItem",
            "ListViewSubItemCollection ListViewVirtualItemsSelectionRangeChangedEventArgs",
            "ListViewVirtualItemsSelectionRangeChangedEventHandler LoadConfigurationEventArgs",
            "LoadConfigurationEventHandler LocalStorage LogManager MainMenu MainMenuConverter MaskedTextBox MaskFormat",
            "MdiChildPage MdiClient MdiLayout MdiTabProperties Media Member MemoryCacheProvider Menu MenuBar MenuBarMenu",
            "MenuButtonItemClickedEventArgs MenuButtonItemClickedEventHandler MenuItem MenuItemCollection",
            "MenuItemEventArgs MenuItemEventHandler MenuItemSizeMode MenuMerge MessageBox MessageBoxButtons",
            "MessageBoxCollection MessageBoxDefaultButton MessageBoxIcon MetaStore MimeTypes ModalFrame MonthCalendar",
            "MonthCalendarExtenestions MouseButtons MouseEventArgs MouseEventHandler MsgBoxResult MsgBoxStyle",
            "NamespaceDoc NodeLabelEditEventArgs NodeLabelEditEventHandler NullDataManager NumericUpDown",
            "NumericUpDownExtensions ObjectCollection ObjectFit OpenFileDialog Orientation Package PackageConverter",
            "Padding PaddingConverter Page PageCollection PageExtensions PaintEventArgs PaintEventHandler",
            "PaintValueEventArgs Panel PanelAutoShowMode PanelCollection PanelExtensions PanelImageProperties PdfViewer",
            "PdfViewerType PictureBox PictureBoxExtensions PictureBoxSizeMode PinchEventArgs PinchEventHandler Placement",
            "PlacementMode PlatformAttribute PlatformLayer PlatformProvider PointerInfo Position",
            "PostbackPropertyAttribute PresetPane PreviewKeyDownEventArgs PreviewKeyDownEventHandler ProgressBar",
            "ProgressBarExtensions ProgressBarStyle Properties PropertyGrid PropertyGridCategoryCell",
            "PropertyGridCategoryRow PropertyGridDataGrid PropertyGridDataRow PropertyGridItem PropertyGridNameCell",
            "PropertyGridNameColumn PropertyGridToolBar PropertyGridValueCell PropertyGridValueColumn",
            "PropertyGridValueRow PropertyManager PropertyNames PropertySort PropertyStore PropertyStoreExtensions",
            "PropertyValueChangedEventArgs PropertyValueChangedEventHandler PropertyValueDataErrorEventArgs",
            "PropertyValueDataErrorEventHandler PropertyValueFormattingEventArgs PropertyValueFormattingEventHandler",
            "PropertyValueTypeDescriptorContext QueryContinueDragEventArgs QueryContinueDragEventHandler QueuedLocker",
            "RadioButton RadioButtonExtensions ReflectedPropertyDescriptor RegexValidationRule RelatedImageListAttribute",
            "RelatedImageSettingsAttribute RequestEventArgs RequestEventHandler RequestType RequiredValidationRule",
            "ResourceManager ResponseActions ResponseManager ResponsiveProfile ResponsiveProfileChangedEventArgs",
            "ResponsiveProfileChangedEventHandler ResponsiveProfileCollection ResponsivePropertyAttribute",
            "ResponsivePropertySourceAttribute RetrieveVirtualItemEventArgs RetrieveVirtualItemEventHandler RightToLeft",
            "RotateEventArgs RotateEventHandler Rotation RowComparer RowStyle RowStyleProxy SameSiteMode SaturationPane",
            "SaveFileDialog Screen ScrollableControl ScrollableControlExtensions ScrollBar ScrollBarExtensions ScrollBars",
            "ScrollBehavior ScrollEventArgs ScrollEventHandler ScrollEventType ScrollOrientation ScrollProperties",
            "SearchForVirtualItemEventArgs SearchForVirtualItemEventHandler SelectedGridItemBeginEditEventArgs",
            "SelectedGridItemBeginEditEventHandler SelectedGridItemChangedEventArgs SelectedGridItemChangedEventHandler",
            "SelectedGridItemEndEditEventArgs SelectedGridItemEndEditEventHandler SelectedIndexCollection",
            "SelectedListViewItemCollection SelectedObjectCollection SelectionMode SelectionRange SelectionRangeConverter",
            "ServiceType Session SessionManager SessionReference SessionStorage SessionTimeoutForm Shape ShapeExtensions",
            "Shortcut SizeType SlideBar SortOrder Spacer SplitButton SplitContainer SplitterCancelEventArgs",
            "SplitterCancelEventHandler SplitterControlExtensions SplitterEventArgs SplitterEventHandler SplitterPanel SR",
            "SRCategoryAttribute SRDescriptionAttribute StatusBar StatusBarControl StatusBarExtensions StatusBarPanel",
            "StatusBarPanelAutoSize StatusBarPanelBorderStyle StatusBarPanelClickEventArgs",
            "StatusBarPanelClickEventHandler StatusBarPanelCollection StyleConverter StyleSheet SummaryRowPosition",
            "SummaryType SwipeAxis SwipeDirection SwipeEventArgs SwipeEventHandler SynchronizedLinkedList",
            "SynchronizedList TabAlignment TabControl TabControlAction TabControlCancelEventArgs",
            "TabControlCancelEventHandler TabControlEventArgs TabControlEventHandler TabControlExtensions",
            "TableLayoutColumnStyleCollection TableLayoutControlCollection TableLayoutEngine TableLayoutPanel",
            "TableLayoutPanelCellPosition TableLayoutPanelExtensions TableLayoutPanelGrowStyle",
            "TableLayoutRowStyleCollection TableLayoutSettings TableLayoutSettingsTypeConverter TableLayoutStyle",
            "TableLayoutStyleCollection TabMdiView TabOrderManager TabOrderManagerDirection TabPage TabPageCollection",
            "TabPageControlCollection TabPageExtensions TabPageImageProperties TabSizeMode TagTextBox TagTextBoxEventArgs",
            "TagTextBoxEventHandler TagTextBoxMousEventArgs TagTextBoxMousEventHandler TagTextBoxRenderEventArgs",
            "TagTextBoxRenderEventHandler TaskBar TelephoneValidationRule TextBox TextBoxBase TextBoxExtensions",
            "TextBoxMode TextBoxType TextDataFormat TextImageRelation TextUtils TickStyle Timer TimerExtensions",
            "TimeUpDown TimeUpDownExtensions TimeUpDownFormat Toast ToolBar ToolBarButton ToolBarButtonClickEventArgs",
            "ToolBarButtonClickEventHandler ToolBarButtonCollection ToolBarButtonExtensions ToolBarButtonSizeMode",
            "ToolBarButtonStyle ToolBarControl ToolBarExtensions ToolBarTextAlign ToolButtonImageProperties",
            "ToolClickEventArgs ToolClickEventHandler ToolTip ToolTipIcon TouchEventArgs TouchEventHandler TrackBar",
            "TrackBarExtensions TrackEventArgs TrackEventHandler TreeNode TreeNodeCollection TreeNodeExtensions",
            "TreeNodeImageProperties TreeNodeMouseClickEventArgs TreeNodeMouseClickEventHandler",
            "TreeNodeMouseHoverEventArgs TreeNodeMouseHoverEventHandler TreeNodeStateImageProperties TreeView",
            "TreeViewAction TreeViewCancelEventArgs TreeViewCancelEventHandler TreeViewComboBox TreeViewEventArgs",
            "TreeViewEventHandler TreeViewExtensions TreeViewNodeDragEventArgs TreeViewNodeDragEventHandler TypedTextBox",
            "TypeValidationEventArgs TypeValidationEventHandler UITypeEditor UITypeEditorEditStyle UpDownBase",
            "UpDownControlExtensions Upload UploadedEventArgs UploadedEventHandler UploadErrorEventArgs",
            "UploadErrorEventHandler UploadErrorType UploadingEventArgs UploadingEventHandler UploadProgressEventArgs",
            "UploadProgressEventHandler UserComboBox UserControl UserPopup Validation ValidationConstraints",
            "ValidationEventArgs ValidationEventHandler ValidationRule ValidationRuleConverter VBoxLayoutEngine",
            "VerticalAlignment Video View ViewModelBase VirtualCellList VirtualCellListEnumerator VirtualDataManager",
            "VirtualDepthLimitedQuickSort VirtualModeItemEnmerator VirtualRowList VirtualRowListEnumerator VScrollBar",
            "VScrollProperties WeakEventHandlerList WeakHandler WebBrowser WebBrowserDocumentCompletedEventArgs",
            "WebBrowserDocumentCompletedEventHandler WebBrowserExtensions WebEventArgs WebEventHandler WebMethodAttribute",
            "WebMethodResult WebRequestEventArgs WebRequestHandler WebSocket Widget WidgetEventArgs WidgetEventHandler",
            "WidgetTarget WindowCollection WiredEvents WisejBodyCompression WisejConfiguration WisejContext",
            "WisejEventArgs WisejExtensions WisejMiddleware WisejResourcesAttribute WisejSerializer",
            "WisejSerializerOptions WisejSerializerOptionsAttribute WisejSynchronizationContext",
        };
    }
}
