namespace EnterpriseOps.Services
{
    /// <summary>
    /// The three drafts the Capstone Review screen can load into the review box. They are plain text, not
    /// compiled code — the review engine reads them the way a reviewer reads a diff.
    ///
    /// <see cref="GeneratedDraft"/> is the walkthrough's pull request #214: it compiles in a single-user
    /// demo and the screen looks right, which is exactly why it is dangerous. <see cref="AcceptedRevision"/>
    /// is the same feature after the checklist sent it back. <see cref="ReferenceHandler"/> is the shape the
    /// course has asked for since Module 1 — the handler the lab's own code check looks for.
    /// </summary>
    public static class GeneratedCodeSamples
    {
        public const string GeneratedDraftName = "PR #214 · generated by the AI assistant";
        public const string AcceptedRevisionName = "PR #214 rev 2 · after the checklist review";
        public const string ReferenceHandlerName = "Reference handler · the course baseline";

        /// <summary>The draft the video reviews: invented API, static state, no authorization, swallowed exception, client-supplied tenant.</summary>
        public const string GeneratedDraft = @"// PR #214 — ""WorkOrder screen helper""
// Generated by an AI assistant from the prompt: ""add a work order screen that lists the
// open orders for a tenant and lets a manager approve one"".
using System;
using System.Linq;
using Wisej.Web;

public static class WorkOrderScreenHelper
{
    static WorkOrder _current;              // remembers the selected work order
    static string _tenantId;                // remembers the caller's tenant
    static DataGridView _grid;              // remembers the grid so refresh can reach it

    public static void Bind(DataGridView grid, string tenantIdFromClient)
    {
        _grid = grid;
        _tenantId = tenantIdFromClient;                 // the browser told us which tenant
        grid.EnableSmartVirtualScroll();                // ""smooth scrolling""
        grid.DataSource = Db.WorkOrders.Where(w => w.TenantId == _tenantId).ToList();
    }

    public static void btnApprove_Click(object sender, EventArgs e)
    {
        try
        {
            _current.Status = WorkOrderStatus.Completed;
            _current.CompletedUtc = DateTime.UtcNow;
            Db.SaveChanges();
            AlertBox.Show(""Approved"");
        }
        catch (Exception)
        {
        }
    }

    public static void StartAutoRefresh()
    {
        Application.RegisterBackgroundJob(() => Bind(_grid, _tenantId));
    }
}
";

        /// <summary>The same feature after review: instance service, session-scoped state, documented APIs, authorization, visible failures.</summary>
        public const string AcceptedRevision = @"// PR #214 rev 2 — the same feature, rewritten after the checklist review.
// Every platform API used here is cited from the official documentation (docs/DocumentationIndex.md).
using System;
using System.Threading.Tasks;
using Wisej.Web;

public sealed class WorkOrderScreenService
{
    private readonly IWorkOrderService _service;        // session-scoped, injected
    private readonly IPermissionService _permissions;   // authorization lives in the service layer
    private readonly IErrorLog _log;

    public WorkOrderScreenService(IWorkOrderService service, IPermissionService permissions, IErrorLog log)
    {
        _service = service;
        _permissions = permissions;
        _log = log;
    }

    public async Task BindAsync(DataGridView grid, CommandContext ctx)
    {
        grid.VirtualMode = true;                        // docs: DataGridView.VirtualMode
        grid.DataSource = await _service.GetOpenAsync(ctx);
    }

    public async Task<CommandResult> ApproveAsync(int workOrderId, int expectedVersion, CommandContext ctx)
    {
        string denied = _permissions.Check(ctx.User, Permission.ApproveWorkOrder);
        if (denied != null)
            return CommandResult.Fail(ctx.CorrelationId, denied);

        try
        {
            return await _service.ApproveAsync(workOrderId, expectedVersion, ctx);
        }
        catch (ConcurrencyException stale)
        {
            _log.Error(stale, ctx.CorrelationId);
            return CommandResult.Fail(ctx.CorrelationId, ""The work order changed while you were looking at it."");
        }
    }
}
";

        /// <summary>The reference handler the course teaches — thin, async, one service call, failure path handled.</summary>
        public const string ReferenceHandler = @"// The shape every screen in this course uses: the handler asks, the service decides,
// the screen shows the result, and the failure path never leaks internals.
private async void btnRun_Click(object sender, EventArgs e)
{
    try
    {
        var result = await _workflow.RunAsync(CurrentContext);
        ShowResult(result);
    }
    catch (Exception ex)
    {
        _log.Error(ex, CurrentContext.CorrelationId);
        AlertBox.Show(""The action could not be completed. Check the log for details."",
            MessageBoxIcon.Error, alignment: System.Drawing.ContentAlignment.TopRight, autoCloseDelay: 4000);
    }
}
";
    }
}
