using SupportDesk.Services;

namespace SupportDesk.Web
{
    partial class TicketEditorForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Wisej.NET Designer generated code

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.editBindingSource = new Wisej.Web.BindingSource(this.components);
            // The Designer-style trick: a Type as DataSource gives every DataBindings.Add below a property to bind to
            // before the real model exists (LoadEditorAsync replaces it with the instance). Without this line Wisej.NET
            // throws "Cannot bind to the property or column Title on the DataSource" while the form is created.
            this.editBindingSource.DataSource = typeof(SupportDesk.Services.TicketEditModel);
            this.errorProvider = new Wisej.Web.ErrorProvider(this.components);
            this.lblNumber = new Wisej.Web.Label();
            this.labelBanner = new Wisej.Web.Label();
            this.lblTitleCaption = new Wisej.Web.Label();
            this.txtTitle = new Wisej.Web.TextBox();
            this.lblDescriptionCaption = new Wisej.Web.Label();
            this.txtDescription = new Wisej.Web.TextBox();
            this.lblCustomerCaption = new Wisej.Web.Label();
            this.cboCustomer = new Wisej.Web.ComboBox();
            this.lblAgentCaption = new Wisej.Web.Label();
            this.cboAgent = new Wisej.Web.ComboBox();
            this.lblCategoryCaption = new Wisej.Web.Label();
            this.cboCategory = new Wisej.Web.ComboBox();
            this.lblStatusCaption = new Wisej.Web.Label();
            this.cboStatus = new Wisej.Web.ComboBox();
            this.lblPriorityCaption = new Wisej.Web.Label();
            this.cboPriority = new Wisej.Web.ComboBox();
            this.lblDueCaption = new Wisej.Web.Label();
            this.dtpDueDate = new Wisej.Web.DateTimePicker();
            this.chkIsUrgent = new Wisej.Web.CheckBox();
            this.btnDelete = new Wisej.Web.Button();
            this.btnCancel = new Wisej.Web.Button();
            this.btnSave = new Wisej.Web.Button();
            this.SuspendLayout();
            //
            // lblNumber  (the ticket number — read only; the lab explains why in TicketEditModel's remarks)
            //
            this.lblNumber.AutoSize = false;
            this.lblNumber.Font = new System.Drawing.Font("default", 12F, System.Drawing.FontStyle.Bold);
            this.lblNumber.ForeColor = System.Drawing.Color.FromArgb(90, 107, 125);
            this.lblNumber.Location = new System.Drawing.Point(24, 16);
            this.lblNumber.Name = "lblNumber";
            this.lblNumber.Size = new System.Drawing.Size(400, 24);
            this.lblNumber.Text = "assigned on save";
            this.lblNumber.ToolTipText = "Number is generated by TicketCommandService.SaveAsync the first time a ticket is saved, and TicketEditModel never carries it — nothing on this screen can renumber a ticket.";
            //
            // labelBanner  (friendly error, hidden until Save/Delete fails)
            //
            this.labelBanner.AutoSize = false;
            this.labelBanner.BackColor = System.Drawing.Color.FromArgb(253, 236, 234);
            this.labelBanner.Font = new System.Drawing.Font("default", 9F, System.Drawing.FontStyle.Bold);
            this.labelBanner.ForeColor = System.Drawing.Color.FromArgb(178, 59, 39);
            this.labelBanner.Location = new System.Drawing.Point(24, 46);
            this.labelBanner.Name = "labelBanner";
            this.labelBanner.Padding = new Wisej.Web.Padding(10, 0, 10, 0);
            this.labelBanner.Size = new System.Drawing.Size(560, 40);
            this.labelBanner.Text = "";
            this.labelBanner.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.labelBanner.Visible = false;
            //
            // lblTitleCaption
            //
            this.lblTitleCaption.AutoSize = false;
            this.lblTitleCaption.ForeColor = System.Drawing.Color.FromArgb(90, 107, 125);
            this.lblTitleCaption.Location = new System.Drawing.Point(24, 96);
            this.lblTitleCaption.Name = "lblTitleCaption";
            this.lblTitleCaption.Size = new System.Drawing.Size(200, 18);
            this.lblTitleCaption.Text = "Title";
            //
            // txtTitle  (the lab control — Text bound OnValidation; the only field Module 4 validates)
            //
            this.txtTitle.Location = new System.Drawing.Point(24, 116);
            this.txtTitle.Name = "txtTitle";
            this.txtTitle.Size = new System.Drawing.Size(560, 30);
            this.txtTitle.DataBindings.Add("Text", this.editBindingSource, nameof(TicketEditModel.Title), true, Wisej.Web.DataSourceUpdateMode.OnValidation);
            //
            // lblDescriptionCaption
            //
            this.lblDescriptionCaption.AutoSize = false;
            this.lblDescriptionCaption.ForeColor = System.Drawing.Color.FromArgb(90, 107, 125);
            this.lblDescriptionCaption.Location = new System.Drawing.Point(24, 154);
            this.lblDescriptionCaption.Name = "lblDescriptionCaption";
            this.lblDescriptionCaption.Size = new System.Drawing.Size(200, 18);
            this.lblDescriptionCaption.Text = "Description";
            //
            // txtDescription  (multiline; Text bound OnValidation)
            //
            this.txtDescription.Location = new System.Drawing.Point(24, 174);
            this.txtDescription.Multiline = true;
            this.txtDescription.Name = "txtDescription";
            this.txtDescription.Size = new System.Drawing.Size(560, 70);
            this.txtDescription.DataBindings.Add("Text", this.editBindingSource, nameof(TicketEditModel.Description), true, Wisej.Web.DataSourceUpdateMode.OnValidation);
            //
            // lblCustomerCaption
            //
            this.lblCustomerCaption.AutoSize = false;
            this.lblCustomerCaption.ForeColor = System.Drawing.Color.FromArgb(90, 107, 125);
            this.lblCustomerCaption.Location = new System.Drawing.Point(24, 254);
            this.lblCustomerCaption.Name = "lblCustomerCaption";
            this.lblCustomerCaption.Size = new System.Drawing.Size(260, 18);
            this.lblCustomerCaption.Text = "Customer";
            //
            // cboCustomer  (lookup: DisplayMember/ValueMember and DataSource set in LoadEditorAsync,
            // BEFORE editBindingSource.DataSource = model — see TicketEditorForm.LoadEditorAsync)
            //
            this.cboCustomer.DropDownStyle = Wisej.Web.ComboBoxStyle.DropDownList;
            this.cboCustomer.Location = new System.Drawing.Point(24, 274);
            this.cboCustomer.Name = "cboCustomer";
            this.cboCustomer.Size = new System.Drawing.Size(260, 30);
            // SelectedValue is bound in TicketEditorForm.BindLookupControls(), after the lookup DataSource and the model exist (see the class remarks).
            //
            // lblAgentCaption
            //
            this.lblAgentCaption.AutoSize = false;
            this.lblAgentCaption.ForeColor = System.Drawing.Color.FromArgb(90, 107, 125);
            this.lblAgentCaption.Location = new System.Drawing.Point(300, 254);
            this.lblAgentCaption.Name = "lblAgentCaption";
            this.lblAgentCaption.Size = new System.Drawing.Size(284, 18);
            this.lblAgentCaption.Text = "Agent";
            //
            // cboAgent  (lookup with a sentinel "— unassigned —" row; Format/Parse map it to a null AgentId
            // — see TicketEditorForm.AgentBinding_Format / _Parse. Everything else here binds a plain int?
            // straight through: nothing selected already means null, no sentinel needed.)
            //
            this.cboAgent.DropDownStyle = Wisej.Web.ComboBoxStyle.DropDownList;
            this.cboAgent.Location = new System.Drawing.Point(300, 274);
            this.cboAgent.Name = "cboAgent";
            this.cboAgent.Size = new System.Drawing.Size(284, 30);
            // SelectedValue is bound in TicketEditorForm.BindLookupControls(), after the lookup DataSource and the model exist (see the class remarks).
            //
            // lblCategoryCaption
            //
            this.lblCategoryCaption.AutoSize = false;
            this.lblCategoryCaption.ForeColor = System.Drawing.Color.FromArgb(90, 107, 125);
            this.lblCategoryCaption.Location = new System.Drawing.Point(24, 314);
            this.lblCategoryCaption.Name = "lblCategoryCaption";
            this.lblCategoryCaption.Size = new System.Drawing.Size(260, 18);
            this.lblCategoryCaption.Text = "Category";
            //
            // cboCategory
            //
            this.cboCategory.DropDownStyle = Wisej.Web.ComboBoxStyle.DropDownList;
            this.cboCategory.Location = new System.Drawing.Point(24, 334);
            this.cboCategory.Name = "cboCategory";
            this.cboCategory.Size = new System.Drawing.Size(260, 30);
            // SelectedValue is bound in TicketEditorForm.BindLookupControls(), after the lookup DataSource and the model exist (see the class remarks).
            //
            // lblStatusCaption
            //
            this.lblStatusCaption.AutoSize = false;
            this.lblStatusCaption.ForeColor = System.Drawing.Color.FromArgb(90, 107, 125);
            this.lblStatusCaption.Location = new System.Drawing.Point(300, 314);
            this.lblStatusCaption.Name = "lblStatusCaption";
            this.lblStatusCaption.Size = new System.Drawing.Size(130, 18);
            this.lblStatusCaption.Text = "Status";
            //
            // cboStatus  (DataSource = TicketStatuses.All, a List<string> — the value IS the display text)
            //
            this.cboStatus.DropDownStyle = Wisej.Web.ComboBoxStyle.DropDownList;
            this.cboStatus.Location = new System.Drawing.Point(300, 334);
            this.cboStatus.Name = "cboStatus";
            this.cboStatus.Size = new System.Drawing.Size(130, 30);
            // SelectedValue is bound in TicketEditorForm.BindLookupControls(), after the lookup DataSource and the model exist (see the class remarks).
            //
            // lblPriorityCaption
            //
            this.lblPriorityCaption.AutoSize = false;
            this.lblPriorityCaption.ForeColor = System.Drawing.Color.FromArgb(90, 107, 125);
            this.lblPriorityCaption.Location = new System.Drawing.Point(446, 314);
            this.lblPriorityCaption.Name = "lblPriorityCaption";
            this.lblPriorityCaption.Size = new System.Drawing.Size(138, 18);
            this.lblPriorityCaption.Text = "Priority";
            //
            // cboPriority  (DataSource = TicketPriorities.All, a List<string>)
            //
            this.cboPriority.DropDownStyle = Wisej.Web.ComboBoxStyle.DropDownList;
            this.cboPriority.Location = new System.Drawing.Point(446, 334);
            this.cboPriority.Name = "cboPriority";
            this.cboPriority.Size = new System.Drawing.Size(138, 30);
            // SelectedValue is bound in TicketEditorForm.BindLookupControls(), after the lookup DataSource and the model exist (see the class remarks).
            //
            // lblDueCaption
            //
            this.lblDueCaption.AutoSize = false;
            this.lblDueCaption.ForeColor = System.Drawing.Color.FromArgb(90, 107, 125);
            this.lblDueCaption.Location = new System.Drawing.Point(24, 374);
            this.lblDueCaption.Name = "lblDueCaption";
            this.lblDueCaption.Size = new System.Drawing.Size(260, 18);
            this.lblDueCaption.Text = "Due date (tick to set)";
            //
            // dtpDueDate  (NOT bound through DataBindings.Add — Checked/Value are copied by hand in
            // LoadEditorAsync/SaveAsync. See the remarks on TicketEditorForm for why: binding a DateTime?
            // model property to the non-nullable Value is flagged unverified in the course cookbook, and
            // the manual copy is the alternative it names.)
            //
            this.dtpDueDate.Format = Wisej.Web.DateTimePickerFormat.Short;
            this.dtpDueDate.Location = new System.Drawing.Point(24, 394);
            this.dtpDueDate.Name = "dtpDueDate";
            this.dtpDueDate.ShowCheckBox = true;
            this.dtpDueDate.Size = new System.Drawing.Size(160, 30);
            //
            // chkIsUrgent
            //
            this.chkIsUrgent.Location = new System.Drawing.Point(300, 394);
            this.chkIsUrgent.Name = "chkIsUrgent";
            this.chkIsUrgent.Size = new System.Drawing.Size(200, 30);
            this.chkIsUrgent.Text = "Urgent";
            this.chkIsUrgent.DataBindings.Add("Checked", this.editBindingSource, nameof(TicketEditModel.IsUrgent), true, Wisej.Web.DataSourceUpdateMode.OnPropertyChanged);
            //
            // btnDelete  (hidden for a new ticket — set in LoadEditorAsync)
            //
            this.btnDelete.ForeColor = System.Drawing.Color.FromArgb(178, 59, 39);
            this.btnDelete.Location = new System.Drawing.Point(24, 470);
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.Size = new System.Drawing.Size(110, 36);
            this.btnDelete.Text = "Delete";
            this.btnDelete.ToolTipText = "Confirms, then TicketCommandService.DeleteAsync: a fresh context, loaded by key, a business rule, then Remove + SaveChangesAsync.";
            this.btnDelete.Click += new System.EventHandler(this.btnDelete_Click);
            //
            // btnCancel  (AcceptButton/CancelButton set below — Cancel writes nothing)
            //
            this.btnCancel.Location = new System.Drawing.Point(390, 470);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(100, 36);
            this.btnCancel.Text = "Cancel";
            this.btnCancel.ToolTipText = "DialogResult.Cancel, no database write — the load context was already disposed by LoadEditorAsync.";
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            //
            // btnSave  (the lab control — EndEdit, validate, fresh context, map, SaveChangesAsync)
            //
            this.btnSave.Font = new System.Drawing.Font("default", 10F, System.Drawing.FontStyle.Bold);
            this.btnSave.Location = new System.Drawing.Point(500, 470);
            this.btnSave.Name = "btnSave";
            this.btnSave.Size = new System.Drawing.Size(100, 36);
            this.btnSave.Text = "Save";
            this.btnSave.ToolTipText = "Guard, EndEdit, the validation placeholder (Title required), a fresh DbContext, load-or-add, map, SaveChangesAsync, DialogResult.OK.";
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            //
            // TicketEditorForm
            //
            this.AcceptButton = this.btnSave;
            this.CancelButton = this.btnCancel;
            this.Controls.Add(this.lblNumber);
            this.Controls.Add(this.labelBanner);
            this.Controls.Add(this.lblTitleCaption);
            this.Controls.Add(this.txtTitle);
            this.Controls.Add(this.lblDescriptionCaption);
            this.Controls.Add(this.txtDescription);
            this.Controls.Add(this.lblCustomerCaption);
            this.Controls.Add(this.cboCustomer);
            this.Controls.Add(this.lblAgentCaption);
            this.Controls.Add(this.cboAgent);
            this.Controls.Add(this.lblCategoryCaption);
            this.Controls.Add(this.cboCategory);
            this.Controls.Add(this.lblStatusCaption);
            this.Controls.Add(this.cboStatus);
            this.Controls.Add(this.lblPriorityCaption);
            this.Controls.Add(this.cboPriority);
            this.Controls.Add(this.lblDueCaption);
            this.Controls.Add(this.dtpDueDate);
            this.Controls.Add(this.chkIsUrgent);
            this.Controls.Add(this.btnDelete);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnSave);
            this.FormBorderStyle = Wisej.Web.FormBorderStyle.Fixed;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "TicketEditorForm";
            this.ShowInTaskbar = false;
            this.Size = new System.Drawing.Size(620, 560);
            this.StartPosition = Wisej.Web.FormStartPosition.CenterParent;
            this.Text = "Add ticket";
            this.Load += new System.EventHandler(this.TicketEditorForm_Load);
            this.ResumeLayout(false);
        }

        #endregion

        private Wisej.Web.BindingSource editBindingSource;
        private Wisej.Web.ErrorProvider errorProvider;
        private Wisej.Web.Label lblNumber;
        private Wisej.Web.Label labelBanner;
        private Wisej.Web.Label lblTitleCaption;
        private Wisej.Web.TextBox txtTitle;
        private Wisej.Web.Label lblDescriptionCaption;
        private Wisej.Web.TextBox txtDescription;
        private Wisej.Web.Label lblCustomerCaption;
        private Wisej.Web.ComboBox cboCustomer;
        private Wisej.Web.Label lblAgentCaption;
        private Wisej.Web.ComboBox cboAgent;
        private Wisej.Web.Label lblCategoryCaption;
        private Wisej.Web.ComboBox cboCategory;
        private Wisej.Web.Label lblStatusCaption;
        private Wisej.Web.ComboBox cboStatus;
        private Wisej.Web.Label lblPriorityCaption;
        private Wisej.Web.ComboBox cboPriority;
        private Wisej.Web.Label lblDueCaption;
        private Wisej.Web.DateTimePicker dtpDueDate;
        private Wisej.Web.CheckBox chkIsUrgent;
        private Wisej.Web.Button btnDelete;
        private Wisej.Web.Button btnCancel;
        private Wisej.Web.Button btnSave;
    }
}
